In [1]:
# 1. Import libraries and load cleaned data

import pandas as pd
import numpy as np
import statsmodels.api as sm

from sklearn.linear_model import LogisticRegression
from sklearn.metrics import (
    brier_score_loss,
    log_loss,
    roc_auc_score
)

# Load cleaned Understat shot data
DATA_PATH = "../data/cleaned/shots_cleaned.csv"

df = pd.read_csv(DATA_PATH)

print(f"Dataset shape: {df.shape}")
print(f"Number of missing values: {df.isnull().sum().sum()}")

df.head()

Dataset shape: (50798, 38)
Number of missing values: 0

,is_home,team,season,xg,minute,result,x,y,angle_to_goal,is_assisted,...,last_action_foul,last_action_head_pass,last_action_lay_off,last_action_none,last_action_pass,last_action_rebound,last_action_standard,last_action_tackle,last_action_take_on,last_action_throughball
0,1,Brentford,2021/22,0.053464,10,0,109.560004,43.120001,0.714539,0,...,0,0,0,0,0,0,0,0,0,0
1,1,Brentford,2021/22,0.118297,11,0,108.960004,25.200000,0.288597,1,...,0,0,0,0,0,0,0,0,0,1
2,1,Brentford,2021/22,0.052145,21,1,104.880002,55.840002,0.275243,1,...,0,0,0,0,0,0,0,0,0,0
3,1,Brentford,2021/22,0.065706,27,0,97.439996,38.239999,0.364677,1,...,0,0,0,0,1,0,0,0,0,0
4,1,Brentford,2021/22,0.080691,29,0,107.039996,28.560001,0.376828,1,...,0,0,0,0,0,0,0,0,0,0

In [2]:

# 2. Define the agreed season split

TRAIN_SEASONS = ["2021/22", "2022/23", "2023/24"]
VAL_SEASONS   = ["2024/25"]
TEST_SEASONS  = ["2025/26"]  # Held out until decisions are frozen

# 2026/27 is excluded because only 60 matches are available so far

# Keep only the agreed seasons
allowed_seasons = TRAIN_SEASONS + VAL_SEASONS + TEST_SEASONS

df = df[df["season"].isin(allowed_seasons)].copy()

# Create chronological train, validation and test datasets
train_df = df[df["season"].isin(TRAIN_SEASONS)].copy()
val_df   = df[df["season"].isin(VAL_SEASONS)].copy()
test_df  = df[df["season"].isin(TEST_SEASONS)].copy()

# Verify the split
print("Training set:", train_df.shape)
print("Validation set:", val_df.shape)
print("Test set:", test_df.shape)

print("\nTraining seasons:")
print(sorted(train_df["season"].unique()))

print("\nValidation seasons:")
print(sorted(val_df["season"].unique()))

print("\nTest seasons:")
print(sorted(test_df["season"].unique()))

Training set: (29813, 38)
Validation set: (9844, 38)
Test set: (9483, 38)

Training seasons:
['2021/22', '2022/23', '2023/24']

Validation seasons:
['2024/25']

Test seasons:
['2025/26']

In [3]:

# 4. Prepare datasets, define predictors and resolve rank deficiency

from scipy.linalg import qr

# Convert Understat coordinates to metres and create spatial features
PITCH_L, PITCH_W = 105, 68

def add_spatial_features(data):
    data = data.copy()

    x_m = data["x"] * PITCH_L / 120
    y_m = data["y"] * PITCH_W / 80

    data["dist_goal_line"] = PITCH_L - x_m
    data["lateral_offset"] = (y_m - PITCH_W / 2).abs()

    return data


# Create the datasets used by the models
train = add_spatial_features(train_df)
val = add_spatial_features(val_df)
test = add_spatial_features(test_df)


# Define predictor groups
CORE_FEATURES = [
    "dist_goal_line",
    "lateral_offset",
    "angle_to_goal"
]

MATCH_FEATURES = [
    "is_home",
    "minute",
    "score_diff"
]

SHOT_FEATURES = [
    "is_assisted",
    "is_penalty",
    "is_open_play",
    "from_corner",
    "is_free_kick"
]

BODY_FEATURES = [
    "left_foot",
    "other_body_part",
    "right_foot"
]

# Exclude categories previously found to cause separation
LAST_ACTION_FEATURES = [
    col for col in train.columns
    if col.startswith("last_action_")
    and col not in ["last_action_none", "last_action_foul"]
]

FULL_FEATURES = (
    CORE_FEATURES
    + MATCH_FEATURES
    + SHOT_FEATURES
    + BODY_FEATURES
    + LAST_ACTION_FEATURES
)

# Check that all specified predictors exist
missing_features = [
    col for col in FULL_FEATURES
    if col not in train.columns
]

if missing_features:
    raise ValueError(
        f"Predictors missing from training data: {missing_features}"
    )

# Check for missing or infinite predictor values
X_check = sm.add_constant(
    train[FULL_FEATURES],
    has_constant="add"
)

if not np.isfinite(X_check.to_numpy()).all():
    raise ValueError(
        "The design matrix contains missing or infinite values."
    )

# Identify linearly dependent columns
X_array = X_check.to_numpy()

_, _, pivot = qr(
    X_array,
    mode="economic",
    pivoting=True
)

rank = np.linalg.matrix_rank(X_array)

independent_cols = [
    X_check.columns[i] for i in pivot[:rank]
]

redundant_cols = [
    col for col in X_check.columns
    if col not in independent_cols
]

print("Original number of columns:", X_check.shape[1])
print("Original matrix rank:", rank)
print("Redundant columns identified:", redundant_cols)

# Remove redundant predictors, keeping the intercept
if "const" in redundant_cols:
    raise ValueError(
        "The intercept was identified as redundant. "
        "Inspect the design matrix."
    )

FULL_FEATURES = [
    col for col in FULL_FEATURES
    if col not in redundant_cols
]

# Verify that the design matrix now has full rank
X_check = sm.add_constant(
    train[FULL_FEATURES],
    has_constant="add"
)

new_rank = np.linalg.matrix_rank(X_check.to_numpy())

print("\nUpdated number of columns:", X_check.shape[1])
print("Updated matrix rank:", new_rank)
print("Removed predictors:", redundant_cols)

assert new_rank == X_check.shape[1], (
    "The design matrix is still rank-deficient."
)

print("\nSuccess: datasets and predictors are ready.")

Original number of columns: 29
Original matrix rank: 28
Redundant columns identified: ['is_free_kick']

Updated number of columns: 28
Updated matrix rank: 28
Removed predictors: ['is_free_kick']

Success: datasets and predictors are ready.

In [4]:

# 5. Fit the full logistic regression model

X_train_full = sm.add_constant(
    train[FULL_FEATURES],
    has_constant="add"
)

y_train = train["result"].to_numpy()

full_fit = sm.Logit(
    y_train,
    X_train_full
).fit(method="lbfgs", maxiter=1000)

print(full_fit.summary())
print("\nConverged:", full_fit.mle_retvals["converged"])

RUNNING THE L-BFGS-B CODE

           * * *

Machine precision = 2.220D-16
 N =           28     M =           10

At X0         0 variables are exactly at the bounds

At iterate    0    f=  6.93147D-01    |proj g|=  1.88477D+01

At iterate    1    f=  4.89100D-01    |proj g|=  4.22737D+00

At iterate    2    f=  4.39995D-01    |proj g|=  3.59864D+00

At iterate    3    f=  3.78370D-01    |proj g|=  1.43259D+00

At iterate    4    f=  3.63823D-01    |proj g|=  1.04063D+00

At iterate    5    f=  3.52397D-01    |proj g|=  1.10438D+00

At iterate    6    f=  3.24472D-01    |proj g|=  1.16503D+00

At iterate    7    f=  3.15309D-01    |proj g|=  1.53850D-01

At iterate    8    f=  3.13283D-01    |proj g|=  8.75863D-02

At iterate    9    f=  3.12322D-01    |proj g|=  7.54453D-02

At iterate   10    f=  3.09989D-01    |proj g|=  6.11176D-02

At iterate   11    f=  3.09211D-01    |proj g|=  3.06904D-02

At iterate   12    f=  3.08780D-01    |proj g|=  1.87649D-02

At iterate   13    f=  3.06682D-01    |proj g|=  1.64350D-01

At iterate   14    f=  3.04531D-01    |proj g|=  2.04866D-01

At iterate   15    f=  3.02174D-01    |proj g|=  4.02821D-01

At iterate   16    f=  3.01019D-01    |proj g|=  2.59206D-01

At iterate   17    f=  3.00727D-01    |proj g|=  2.63817D-02

At iterate   18    f=  3.00668D-01    |proj g|=  4.88220D-02

At iterate   19    f=  3.00633D-01    |proj g|=  5.60864D-02

At iterate   20    f=  3.00324D-01    |proj g|=  7.53696D-02

At iterate   21    f=  2.99553D-01    |proj g|=  1.13414D-01

At iterate   22    f=  2.97790D-01    |proj g|=  1.85414D-01

At iterate   23    f=  2.95702D-01    |proj g|=  1.49337D-01

At iterate   24    f=  2.93943D-01    |proj g|=  3.95059D-01

At iterate   25    f=  2.92682D-01    |proj g|=  1.03811D-01

At iterate   26    f=  2.92437D-01    |proj g|=  5.44013D-03

At iterate   27    f=  2.92411D-01    |proj g|=  1.48701D-02

At iterate   28    f=  2.92327D-01    |proj g|=  8.09082D-02

At iterate   29    f=  2.92292D-01    |proj g|=  1.05042D-01

At iterate   30    f=  2.92213D-01    |proj g|=  1.88335D-02

At iterate   31    f=  2.92172D-01    |proj g|=  2.72403D-02

At iterate   32    f=  2.92052D-01    |proj g|=  3.84262D-02

At iterate   33    f=  2.91669D-01    |proj g|=  6.41398D-02

At iterate   34    f=  2.90742D-01    |proj g|=  9.93476D-02

At iterate   35    f=  2.90030D-01    |proj g|=  3.39645D-02

At iterate   36    f=  2.89628D-01    |proj g|=  5.43478D-02

At iterate   37    f=  2.89215D-01    |proj g|=  1.69632D-01

At iterate   38    f=  2.88476D-01    |proj g|=  7.14459D-02

At iterate   39    f=  2.88118D-01    |proj g|=  2.79851D-02

At iterate   40    f=  2.87930D-01    |proj g|=  1.35905D-01

At iterate   41    f=  2.87758D-01    |proj g|=  1.15344D-01

At iterate   42    f=  2.87620D-01    |proj g|=  3.50754D-02

At iterate   43    f=  2.87475D-01    |proj g|=  4.61971D-02

At iterate   44    f=  2.87455D-01    |proj g|=  2.30217D-02

At iterate   45    f=  2.87448D-01    |proj g|=  5.05042D-03

At iterate   46    f=  2.87445D-01    |proj g|=  1.39607D-02

At iterate   47    f=  2.87439D-01    |proj g|=  3.09741D-02

At iterate   48    f=  2.87424D-01    |proj g|=  5.48646D-02

At iterate   49    f=  2.87389D-01    |proj g|=  8.33146D-02

At iterate   50    f=  2.87316D-01    |proj g|=  1.02918D-01

At iterate   51    f=  2.87203D-01    |proj g|=  1.48104D-01

At iterate   52    f=  2.87168D-01    |proj g|=  4.10513D-02

At iterate   53    f=  2.87104D-01    |proj g|=  2.14717D-02

At iterate   54    f=  2.87054D-01    |proj g|=  1.47032D-02

At iterate   55    f=  2.87040D-01    |proj g|=  2.45042D-02

At iterate   56    f=  2.86937D-01    |proj g|=  6.45501D-02

At iterate   57    f=  2.86802D-01    |proj g|=  5.43327D-02

At iterate   58    f=  2.86636D-01    |proj g|=  3.71218D-02

At iterate   59    f=  2.86557D-01    |proj g|=  1.45792D-02

At iterate   60    f=  2.86492D-01    |proj g|=  1.27802D-02

At iterate   61    f=  2.86427D-01    |proj g|=  7.40334D-02

At iterate   62    f=  2.86319D-01    |proj g|=  4.14816D-02

At iterate   63    f=  2.86123D-01    |proj g|=  1.58708D-01

At iterate   64    f=  2.85943D-01    |proj g|=  2.81655D-01

At iterate   65    f=  2.85567D-01    |proj g|=  7.54326D-02

At iterate   66    f=  2.85268D-01    |proj g|=  4.54750D-02

At iterate   67    f=  2.85204D-01    |proj g|=  2.91606D-02

At iterate   68    f=  2.85200D-01    |proj g|=  3.13646D-02

At iterate   69    f=  2.85177D-01    |proj g|=  4.15713D-02

At iterate   70    f=  2.85159D-01    |proj g|=  4.54581D-02

At iterate   71    f=  2.85079D-01    |proj g|=  5.13257D-02

At iterate   72    f=  2.84927D-01    |proj g|=  4.93551D-02

At iterate   73    f=  2.84912D-01    |proj g|=  6.06492D-02

At iterate   74    f=  2.84830D-01    |proj g|=  1.32158D-02

At iterate   75    f=  2.84682D-01    |proj g|=  2.63518D-02

At iterate   76    f=  2.84573D-01    |proj g|=  1.16533D-01

At iterate   77    f=  2.84458D-01    |proj g|=  3.33686D-02

At iterate   78    f=  2.84415D-01    |proj g|=  5.92041D-03

At iterate   79    f=  2.84329D-01    |proj g|=  3.67346D-02

At iterate   80    f=  2.84258D-01    |proj g|=  1.09374D-02

At iterate   81    f=  2.84195D-01    |proj g|=  8.28946D-02

At iterate   82    f=  2.84120D-01    |proj g|=  5.02719D-02

At iterate   83    f=  2.84052D-01    |proj g|=  4.94049D-03

At iterate   84    f=  2.84050D-01    |proj g|=  2.49768D-03

 This problem is unconstrained.

At iterate   85    f=  2.84046D-01    |proj g|=  2.52664D-03

At iterate   86    f=  2.84044D-01    |proj g|=  1.10232D-02

At iterate   87    f=  2.84041D-01    |proj g|=  7.28401D-03

At iterate   88    f=  2.84030D-01    |proj g|=  2.18097D-02

At iterate   89    f=  2.84015D-01    |proj g|=  2.66282D-02

At iterate   90    f=  2.83990D-01    |proj g|=  2.33612D-02

At iterate   91    f=  2.83761D-01    |proj g|=  2.25074D-02

At iterate   92    f=  2.83575D-01    |proj g|=  6.76390D-02

At iterate   93    f=  2.83241D-01    |proj g|=  4.71194D-02

At iterate   94    f=  2.83125D-01    |proj g|=  1.35559D-01

At iterate   95    f=  2.82898D-01    |proj g|=  5.62975D-02

At iterate   96    f=  2.82754D-01    |proj g|=  2.55210D-02

At iterate   97    f=  2.82747D-01    |proj g|=  1.06358D-02

At iterate   98    f=  2.82742D-01    |proj g|=  2.88937D-03

At iterate   99    f=  2.82736D-01    |proj g|=  1.33958D-02

At iterate  100    f=  2.82727D-01    |proj g|=  1.44306D-02

At iterate  101    f=  2.82726D-01    |proj g|=  2.93971D-02

At iterate  102    f=  2.82719D-01    |proj g|=  2.01862D-02

At iterate  103    f=  2.82709D-01    |proj g|=  1.12781D-02

At iterate  104    f=  2.82691D-01    |proj g|=  6.53135D-03

At iterate  105    f=  2.82683D-01    |proj g|=  2.56729D-02

At iterate  106    f=  2.82679D-01    |proj g|=  4.34102D-03

At iterate  107    f=  2.82676D-01    |proj g|=  4.74606D-03

At iterate  108    f=  2.82670D-01    |proj g|=  1.63184D-02

At iterate  109    f=  2.82665D-01    |proj g|=  1.33511D-02

At iterate  110    f=  2.82647D-01    |proj g|=  2.59348D-03

At iterate  111    f=  2.82638D-01    |proj g|=  5.41636D-03

At iterate  112    f=  2.82626D-01    |proj g|=  2.61370D-02

At iterate  113    f=  2.82602D-01    |proj g|=  1.17445D-02

At iterate  114    f=  2.82566D-01    |proj g|=  1.20157D-02

At iterate  115    f=  2.82511D-01    |proj g|=  1.80616D-01

At iterate  116    f=  2.82157D-01    |proj g|=  2.26031D-02

At iterate  117    f=  2.82008D-01    |proj g|=  4.99897D-02

At iterate  118    f=  2.81869D-01    |proj g|=  2.44513D-02

At iterate  119    f=  2.81865D-01    |proj g|=  4.41549D-02

At iterate  120    f=  2.81851D-01    |proj g|=  1.04966D-02

At iterate  121    f=  2.81848D-01    |proj g|=  4.09302D-03

At iterate  122    f=  2.81846D-01    |proj g|=  5.30786D-03

At iterate  123    f=  2.81844D-01    |proj g|=  1.45046D-02

At iterate  124    f=  2.81842D-01    |proj g|=  5.83546D-03

At iterate  125    f=  2.81841D-01    |proj g|=  8.69543D-03

At iterate  126    f=  2.81838D-01    |proj g|=  1.50078D-02

At iterate  127    f=  2.81834D-01    |proj g|=  1.10672D-02

At iterate  128    f=  2.81831D-01    |proj g|=  1.37495D-02

At iterate  129    f=  2.81822D-01    |proj g|=  3.48546D-02

At iterate  130    f=  2.81814D-01    |proj g|=  2.27249D-02

At iterate  131    f=  2.81800D-01    |proj g|=  8.36449D-03

At iterate  132    f=  2.81775D-01    |proj g|=  1.11766D-02

At iterate  133    f=  2.81730D-01    |proj g|=  2.47467D-02

At iterate  134    f=  2.81660D-01    |proj g|=  4.73371D-02

At iterate  135    f=  2.81649D-01    |proj g|=  1.16577D-02

At iterate  136    f=  2.81589D-01    |proj g|=  2.34134D-02

At iterate  137    f=  2.81568D-01    |proj g|=  1.84936D-02

At iterate  138    f=  2.81551D-01    |proj g|=  6.72842D-03

At iterate  139    f=  2.81541D-01    |proj g|=  1.93833D-02

At iterate  140    f=  2.81527D-01    |proj g|=  2.22852D-02

At iterate  141    f=  2.81497D-01    |proj g|=  3.73167D-02

At iterate  142    f=  2.81475D-01    |proj g|=  1.21413D-02

At iterate  143    f=  2.81457D-01    |proj g|=  1.17961D-02

At iterate  144    f=  2.81434D-01    |proj g|=  3.35969D-02

At iterate  145    f=  2.81393D-01    |proj g|=  1.22240D-02

At iterate  146    f=  2.81344D-01    |proj g|=  2.04832D-02

At iterate  147    f=  2.81340D-01    |proj g|=  5.30014D-03

At iterate  148    f=  2.81333D-01    |proj g|=  5.23014D-03

At iterate  149    f=  2.81331D-01    |proj g|=  2.65934D-03

At iterate  150    f=  2.81327D-01    |proj g|=  6.59815D-03

At iterate  151    f=  2.81321D-01    |proj g|=  1.38415D-02

At iterate  152    f=  2.81307D-01    |proj g|=  2.33078D-02

At iterate  153    f=  2.81284D-01    |proj g|=  3.23407D-02

At iterate  154    f=  2.81277D-01    |proj g|=  1.29697D-02

At iterate  155    f=  2.81257D-01    |proj g|=  2.01735D-02

At iterate  156    f=  2.81247D-01    |proj g|=  3.93342D-03

At iterate  157    f=  2.81245D-01    |proj g|=  1.69849D-03

At iterate  158    f=  2.81244D-01    |proj g|=  7.41538D-03

At iterate  159    f=  2.81241D-01    |proj g|=  9.62137D-03

At iterate  160    f=  2.81238D-01    |proj g|=  2.43619D-02

At iterate  161    f=  2.81233D-01    |proj g|=  1.19639D-02

At iterate  162    f=  2.81229D-01    |proj g|=  4.76522D-03

At iterate  163    f=  2.81225D-01    |proj g|=  1.18940D-02

At iterate  164    f=  2.81219D-01    |proj g|=  2.06289D-02

At iterate  165    f=  2.81211D-01    |proj g|=  1.30637D-02

At iterate  166    f=  2.81210D-01    |proj g|=  2.72345D-02

At iterate  167    f=  2.81206D-01    |proj g|=  7.54545D-03

At iterate  168    f=  2.81205D-01    |proj g|=  2.51293D-03

At iterate  169    f=  2.81205D-01    |proj g|=  3.26649D-03

At iterate  170    f=  2.81203D-01    |proj g|=  5.90022D-03

At iterate  171    f=  2.81202D-01    |proj g|=  3.59650D-03

At iterate  172    f=  2.81202D-01    |proj g|=  2.36400D-03

At iterate  173    f=  2.81200D-01    |proj g|=  2.63415D-03

At iterate  174    f=  2.81197D-01    |proj g|=  9.86571D-03

At iterate  175    f=  2.81187D-01    |proj g|=  1.01105D-02

At iterate  176    f=  2.81157D-01    |proj g|=  7.21969D-03

At iterate  177    f=  2.81115D-01    |proj g|=  2.57866D-02

At iterate  178    f=  2.81103D-01    |proj g|=  3.16060D-02

At iterate  179    f=  2.81076D-01    |proj g|=  1.95572D-02

At iterate  180    f=  2.81058D-01    |proj g|=  1.33704D-02

At iterate  181    f=  2.81054D-01    |proj g|=  1.68422D-03

At iterate  182    f=  2.81052D-01    |proj g|=  2.24860D-03

At iterate  183    f=  2.81047D-01    |proj g|=  2.11708D-02

At iterate  184    f=  2.81037D-01    |proj g|=  1.46358D-02

At iterate  185    f=  2.81027D-01    |proj g|=  4.65036D-03

At iterate  186    f=  2.81022D-01    |proj g|=  3.27669D-03

At iterate  187    f=  2.81018D-01    |proj g|=  2.88052D-03

At iterate  188    f=  2.81017D-01    |proj g|=  1.03859D-02

At iterate  189    f=  2.81014D-01    |proj g|=  1.29881D-02

At iterate  190    f=  2.81011D-01    |proj g|=  9.35001D-03

At iterate  191    f=  2.81006D-01    |proj g|=  3.19397D-02

At iterate  192    f=  2.80996D-01    |proj g|=  7.09674D-03

At iterate  193    f=  2.80984D-01    |proj g|=  7.77326D-03

At iterate  194    f=  2.80942D-01    |proj g|=  4.81565D-02

At iterate  195    f=  2.80887D-01    |proj g|=  7.62497D-02

At iterate  196    f=  2.80808D-01    |proj g|=  7.10574D-02

At iterate  197    f=  2.80802D-01    |proj g|=  9.29745D-02

At iterate  198    f=  2.80739D-01    |proj g|=  4.83041D-02

At iterate  199    f=  2.80710D-01    |proj g|=  1.19494D-02

At iterate  200    f=  2.80702D-01    |proj g|=  2.09269D-02

At iterate  201    f=  2.80698D-01    |proj g|=  1.86740D-02

At iterate  202    f=  2.80697D-01    |proj g|=  2.52344D-02

At iterate  203    f=  2.80694D-01    |proj g|=  1.78175D-03

At iterate  204    f=  2.80694D-01    |proj g|=  1.73477D-03

At iterate  205    f=  2.80693D-01    |proj g|=  2.73154D-03

At iterate  206    f=  2.80690D-01    |proj g|=  7.84204D-03

At iterate  207    f=  2.80686D-01    |proj g|=  1.18371D-02

At iterate  208    f=  2.80679D-01    |proj g|=  1.08712D-02

At iterate  209    f=  2.80670D-01    |proj g|=  2.11785D-02

At iterate  210    f=  2.80665D-01    |proj g|=  7.57501D-03

At iterate  211    f=  2.80655D-01    |proj g|=  4.94135D-03

At iterate  212    f=  2.80632D-01    |proj g|=  1.14879D-02

At iterate  213    f=  2.80616D-01    |proj g|=  9.37312D-03

At iterate  214    f=  2.80615D-01    |proj g|=  2.65748D-02

At iterate  215    f=  2.80596D-01    |proj g|=  1.22345D-02

At iterate  216    f=  2.80586D-01    |proj g|=  7.51924D-03

At iterate  217    f=  2.80579D-01    |proj g|=  5.48324D-03

At iterate  218    f=  2.80574D-01    |proj g|=  4.24699D-03

At iterate  219    f=  2.80569D-01    |proj g|=  2.83246D-03

At iterate  220    f=  2.80567D-01    |proj g|=  3.25918D-03

At iterate  221    f=  2.80566D-01    |proj g|=  3.61253D-03

At iterate  222    f=  2.80564D-01    |proj g|=  8.23864D-03

At iterate  223    f=  2.80563D-01    |proj g|=  1.79366D-03

At iterate  224    f=  2.80562D-01    |proj g|=  3.40701D-03

At iterate  225    f=  2.80561D-01    |proj g|=  1.47768D-03

At iterate  226    f=  2.80561D-01    |proj g|=  9.69879D-03

At iterate  227    f=  2.80560D-01    |proj g|=  2.27059D-03

At iterate  228    f=  2.80559D-01    |proj g|=  2.39822D-03

At iterate  229    f=  2.80558D-01    |proj g|=  5.41406D-03

At iterate  230    f=  2.80556D-01    |proj g|=  5.71430D-03

At iterate  231    f=  2.80554D-01    |proj g|=  6.50110D-03

At iterate  232    f=  2.80553D-01    |proj g|=  1.68131D-02

At iterate  233    f=  2.80551D-01    |proj g|=  7.54844D-03

At iterate  234    f=  2.80549D-01    |proj g|=  1.92227D-03

At iterate  235    f=  2.80549D-01    |proj g|=  4.29432D-03

At iterate  236    f=  2.80548D-01    |proj g|=  4.10402D-03

At iterate  237    f=  2.80548D-01    |proj g|=  8.42950D-03

At iterate  238    f=  2.80548D-01    |proj g|=  4.99137D-03

At iterate  239    f=  2.80548D-01    |proj g|=  8.18707D-04

At iterate  240    f=  2.80547D-01    |proj g|=  2.06134D-03

At iterate  241    f=  2.80547D-01    |proj g|=  5.59626D-03

At iterate  242    f=  2.80547D-01    |proj g|=  9.60288D-03

At iterate  243    f=  2.80545D-01    |proj g|=  1.50367D-02

At iterate  244    f=  2.80542D-01    |proj g|=  1.84380D-02

At iterate  245    f=  2.80539D-01    |proj g|=  1.33196D-02

At iterate  246    f=  2.80538D-01    |proj g|=  1.81591D-02

At iterate  247    f=  2.80534D-01    |proj g|=  4.90270D-03

At iterate  248    f=  2.80532D-01    |proj g|=  7.09520D-03

At iterate  249    f=  2.80530D-01    |proj g|=  2.00413D-02

At iterate  250    f=  2.80527D-01    |proj g|=  4.71692D-03

At iterate  251    f=  2.80525D-01    |proj g|=  8.86463D-03

At iterate  252    f=  2.80523D-01    |proj g|=  1.92345D-03

At iterate  253    f=  2.80522D-01    |proj g|=  1.29701D-03

At iterate  254    f=  2.80519D-01    |proj g|=  3.74034D-03

At iterate  255    f=  2.80517D-01    |proj g|=  8.49131D-03

At iterate  256    f=  2.80508D-01    |proj g|=  1.48718D-02

At iterate  257    f=  2.80501D-01    |proj g|=  1.07452D-02

At iterate  258    f=  2.80499D-01    |proj g|=  2.42647D-02

At iterate  259    f=  2.80494D-01    |proj g|=  6.83564D-03

At iterate  260    f=  2.80493D-01    |proj g|=  2.77655D-03

At iterate  261    f=  2.80493D-01    |proj g|=  3.94195D-03

At iterate  262    f=  2.80491D-01    |proj g|=  5.10261D-03

At iterate  263    f=  2.80491D-01    |proj g|=  1.86697D-02

At iterate  264    f=  2.80487D-01    |proj g|=  1.38373D-02

At iterate  265    f=  2.80482D-01    |proj g|=  4.71349D-03

At iterate  266    f=  2.80478D-01    |proj g|=  3.81190D-03

At iterate  267    f=  2.80475D-01    |proj g|=  7.23844D-03

At iterate  268    f=  2.80473D-01    |proj g|=  6.39146D-03

At iterate  269    f=  2.80473D-01    |proj g|=  1.06698D-02

At iterate  270    f=  2.80471D-01    |proj g|=  3.39556D-03

At iterate  271    f=  2.80470D-01    |proj g|=  2.24628D-03

At iterate  272    f=  2.80470D-01    |proj g|=  3.27062D-03

At iterate  273    f=  2.80470D-01    |proj g|=  2.83107D-03

At iterate  274    f=  2.80469D-01    |proj g|=  5.41824D-03

At iterate  275    f=  2.80468D-01    |proj g|=  5.91857D-03

At iterate  276    f=  2.80467D-01    |proj g|=  2.64871D-03

At iterate  277    f=  2.80465D-01    |proj g|=  2.26178D-03

At iterate  278    f=  2.80461D-01    |proj g|=  3.19486D-03

At iterate  279    f=  2.80456D-01    |proj g|=  1.54341D-02

At iterate  280    f=  2.80449D-01    |proj g|=  1.51709D-02

At iterate  281    f=  2.80448D-01    |proj g|=  1.75498D-02

At iterate  282    f=  2.80434D-01    |proj g|=  3.18769D-03

At iterate  283    f=  2.80423D-01    |proj g|=  2.52745D-03

At iterate  284    f=  2.80422D-01    |proj g|=  1.20690D-02

At iterate  285    f=  2.80417D-01    |proj g|=  5.36321D-03

At iterate  286    f=  2.80416D-01    |proj g|=  9.15396D-03

At iterate  287    f=  2.80415D-01    |proj g|=  4.62389D-03

At iterate  288    f=  2.80415D-01    |proj g|=  4.41644D-03

At iterate  289    f=  2.80413D-01    |proj g|=  1.88550D-03

At iterate  290    f=  2.80408D-01    |proj g|=  2.71247D-03

At iterate  291    f=  2.80394D-01    |proj g|=  7.56535D-03

At iterate  292    f=  2.80365D-01    |proj g|=  5.26029D-03

At iterate  293    f=  2.80358D-01    |proj g|=  1.46424D-02

At iterate  294    f=  2.80350D-01    |proj g|=  7.00430D-03

At iterate  295    f=  2.80344D-01    |proj g|=  5.81994D-03

At iterate  296    f=  2.80343D-01    |proj g|=  1.08322D-02

At iterate  297    f=  2.80341D-01    |proj g|=  2.49578D-03

At iterate  298    f=  2.80341D-01    |proj g|=  7.10015D-03

At iterate  299    f=  2.80340D-01    |proj g|=  7.96838D-03

At iterate  300    f=  2.80340D-01    |proj g|=  1.11640D-02

At iterate  301    f=  2.80339D-01    |proj g|=  3.33576D-03

At iterate  302    f=  2.80339D-01    |proj g|=  2.70042D-03

At iterate  303    f=  2.80338D-01    |proj g|=  8.47142D-03

At iterate  304    f=  2.80338D-01    |proj g|=  1.27904D-02

At iterate  305    f=  2.80337D-01    |proj g|=  1.31326D-02

At iterate  306    f=  2.80335D-01    |proj g|=  2.69168D-03

At iterate  307    f=  2.80334D-01    |proj g|=  1.69051D-03

At iterate  308    f=  2.80330D-01    |proj g|=  1.45071D-02

At iterate  309    f=  2.80329D-01    |proj g|=  1.14999D-02

At iterate  310    f=  2.80328D-01    |proj g|=  1.39825D-02

At iterate  311    f=  2.80327D-01    |proj g|=  4.90463D-03

At iterate  312    f=  2.80326D-01    |proj g|=  2.76058D-03

At iterate  313    f=  2.80324D-01    |proj g|=  2.96313D-03

At iterate  314    f=  2.80321D-01    |proj g|=  1.20910D-02

At iterate  315    f=  2.80319D-01    |proj g|=  5.20055D-03

At iterate  316    f=  2.80318D-01    |proj g|=  1.50402D-03

At iterate  317    f=  2.80317D-01    |proj g|=  3.80046D-03

At iterate  318    f=  2.80317D-01    |proj g|=  5.07675D-03

At iterate  319    f=  2.80315D-01    |proj g|=  3.76849D-03

At iterate  320    f=  2.80313D-01    |proj g|=  1.41324D-02

At iterate  321    f=  2.80309D-01    |proj g|=  7.02235D-03

At iterate  322    f=  2.80300D-01    |proj g|=  2.64942D-03

At iterate  323    f=  2.80297D-01    |proj g|=  1.96075D-02

At iterate  324    f=  2.80295D-01    |proj g|=  4.13427D-03

At iterate  325    f=  2.80294D-01    |proj g|=  4.02120D-03

At iterate  326    f=  2.80293D-01    |proj g|=  1.04054D-02

At iterate  327    f=  2.80291D-01    |proj g|=  6.86052D-03

At iterate  328    f=  2.80290D-01    |proj g|=  4.03320D-03

At iterate  329    f=  2.80288D-01    |proj g|=  1.60344D-03

At iterate  330    f=  2.80288D-01    |proj g|=  1.29153D-03

At iterate  331    f=  2.80288D-01    |proj g|=  3.72345D-03

At iterate  332    f=  2.80288D-01    |proj g|=  2.34759D-03

At iterate  333    f=  2.80288D-01    |proj g|=  1.46986D-03

At iterate  334    f=  2.80287D-01    |proj g|=  3.17007D-03

At iterate  335    f=  2.80287D-01    |proj g|=  2.99765D-03

At iterate  336    f=  2.80287D-01    |proj g|=  2.33948D-03

At iterate  337    f=  2.80287D-01    |proj g|=  8.33924D-03

At iterate  338    f=  2.80286D-01    |proj g|=  1.26859D-03

At iterate  339    f=  2.80285D-01    |proj g|=  1.03912D-03

At iterate  340    f=  2.80285D-01    |proj g|=  1.39879D-03

At iterate  341    f=  2.80285D-01    |proj g|=  1.51129D-03

At iterate  342    f=  2.80285D-01    |proj g|=  1.16813D-03

At iterate  343    f=  2.80285D-01    |proj g|=  6.09619D-04

At iterate  344    f=  2.80285D-01    |proj g|=  3.86900D-04

At iterate  345    f=  2.80285D-01    |proj g|=  3.92120D-03

At iterate  346    f=  2.80284D-01    |proj g|=  3.43184D-03

At iterate  347    f=  2.80282D-01    |proj g|=  2.05886D-02

At iterate  348    f=  2.80279D-01    |proj g|=  6.65263D-03

At iterate  349    f=  2.80275D-01    |proj g|=  5.08154D-03

At iterate  350    f=  2.80274D-01    |proj g|=  2.33714D-03

At iterate  351    f=  2.80274D-01    |proj g|=  7.18279D-03

At iterate  352    f=  2.80273D-01    |proj g|=  1.09372D-03

At iterate  353    f=  2.80273D-01    |proj g|=  3.16856D-03

At iterate  354    f=  2.80273D-01    |proj g|=  4.72215D-03

At iterate  355    f=  2.80272D-01    |proj g|=  1.40747D-03

At iterate  356    f=  2.80272D-01    |proj g|=  6.11952D-04

At iterate  357    f=  2.80272D-01    |proj g|=  2.74110D-03

At iterate  358    f=  2.80272D-01    |proj g|=  5.30828D-03

At iterate  359    f=  2.80272D-01    |proj g|=  5.57751D-03

At iterate  360    f=  2.80272D-01    |proj g|=  7.32114D-03

At iterate  361    f=  2.80272D-01    |proj g|=  3.12611D-03

At iterate  362    f=  2.80271D-01    |proj g|=  1.47514D-03

At iterate  363    f=  2.80271D-01    |proj g|=  2.75927D-03

At iterate  364    f=  2.80271D-01    |proj g|=  3.88958D-03

At iterate  365    f=  2.80271D-01    |proj g|=  5.94069D-03

At iterate  366    f=  2.80271D-01    |proj g|=  1.66743D-03

At iterate  367    f=  2.80271D-01    |proj g|=  2.75504D-03

At iterate  368    f=  2.80269D-01    |proj g|=  4.13812D-03

At iterate  369    f=  2.80269D-01    |proj g|=  6.08237D-03

At iterate  370    f=  2.80266D-01    |proj g|=  5.82974D-03

At iterate  371    f=  2.80263D-01    |proj g|=  2.44252D-03

At iterate  372    f=  2.80256D-01    |proj g|=  1.32987D-02

At iterate  373    f=  2.80256D-01    |proj g|=  9.48768D-04

At iterate  374    f=  2.80255D-01    |proj g|=  7.07211D-04

At iterate  375    f=  2.80255D-01    |proj g|=  1.74264D-03

At iterate  376    f=  2.80255D-01    |proj g|=  1.85251D-03

At iterate  377    f=  2.80254D-01    |proj g|=  4.29113D-04

At iterate  378    f=  2.80254D-01    |proj g|=  8.22343D-04

At iterate  379    f=  2.80254D-01    |proj g|=  8.37317D-04

At iterate  380    f=  2.80254D-01    |proj g|=  4.82022D-04

At iterate  381    f=  2.80254D-01    |proj g|=  3.18965D-04

At iterate  382    f=  2.80253D-01    |proj g|=  2.19015D-03

At iterate  383    f=  2.80253D-01    |proj g|=  5.50903D-04

At iterate  384    f=  2.80253D-01    |proj g|=  6.24824D-03

At iterate  385    f=  2.80253D-01    |proj g|=  1.81591D-03

At iterate  386    f=  2.80253D-01    |proj g|=  6.26426D-04

At iterate  387    f=  2.80253D-01    |proj g|=  3.39715D-03

At iterate  388    f=  2.80252D-01    |proj g|=  6.01511D-03

At iterate  389    f=  2.80252D-01    |proj g|=  7.15192D-03

At iterate  390    f=  2.80251D-01    |proj g|=  6.63297D-03

At iterate  391    f=  2.80251D-01    |proj g|=  3.30791D-03

At iterate  392    f=  2.80251D-01    |proj g|=  4.20431D-04

At iterate  393    f=  2.80250D-01    |proj g|=  4.21173D-03

At iterate  394    f=  2.80250D-01    |proj g|=  6.00495D-03

At iterate  395    f=  2.80250D-01    |proj g|=  8.92917D-03

At iterate  396    f=  2.80249D-01    |proj g|=  8.06255D-03

At iterate  397    f=  2.80249D-01    |proj g|=  1.34371D-02

At iterate  398    f=  2.80248D-01    |proj g|=  8.00945D-03

At iterate  399    f=  2.80247D-01    |proj g|=  2.89217D-03

At iterate  400    f=  2.80246D-01    |proj g|=  2.53853D-03

At iterate  401    f=  2.80245D-01    |proj g|=  4.01929D-03

At iterate  402    f=  2.80244D-01    |proj g|=  1.59596D-03

At iterate  403    f=  2.80243D-01    |proj g|=  2.11004D-03

At iterate  404    f=  2.80243D-01    |proj g|=  2.54142D-03

At iterate  405    f=  2.80243D-01    |proj g|=  3.12666D-03

At iterate  406    f=  2.80242D-01    |proj g|=  4.09699D-03

At iterate  407    f=  2.80241D-01    |proj g|=  3.12897D-03

At iterate  408    f=  2.80240D-01    |proj g|=  1.46233D-02

At iterate  409    f=  2.80238D-01    |proj g|=  8.60780D-03

At iterate  410    f=  2.80236D-01    |proj g|=  4.85877D-03

At iterate  411    f=  2.80235D-01    |proj g|=  5.50339D-03

At iterate  412    f=  2.80234D-01    |proj g|=  1.00974D-03

At iterate  413    f=  2.80234D-01    |proj g|=  2.30574D-04

At iterate  414    f=  2.80234D-01    |proj g|=  2.32347D-04

At iterate  415    f=  2.80234D-01    |proj g|=  3.12912D-03

At iterate  416    f=  2.80234D-01    |proj g|=  6.91276D-04

At iterate  417    f=  2.80234D-01    |proj g|=  4.29200D-04

At iterate  418    f=  2.80234D-01    |proj g|=  1.22377D-03

At iterate  419    f=  2.80234D-01    |proj g|=  9.45657D-04

At iterate  420    f=  2.80234D-01    |proj g|=  4.95387D-03

At iterate  421    f=  2.80233D-01    |proj g|=  2.34522D-03

At iterate  422    f=  2.80233D-01    |proj g|=  7.74993D-04

At iterate  423    f=  2.80233D-01    |proj g|=  1.44105D-03

At iterate  424    f=  2.80232D-01    |proj g|=  5.58782D-03

At iterate  425    f=  2.80232D-01    |proj g|=  2.64506D-03

At iterate  426    f=  2.80232D-01    |proj g|=  1.34289D-03

At iterate  427    f=  2.80231D-01    |proj g|=  5.29105D-03

At iterate  428    f=  2.80231D-01    |proj g|=  6.95251D-03

At iterate  429    f=  2.80230D-01    |proj g|=  3.16474D-03

At iterate  430    f=  2.80230D-01    |proj g|=  2.03436D-03

At iterate  431    f=  2.80230D-01    |proj g|=  1.19949D-03

At iterate  432    f=  2.80230D-01    |proj g|=  2.27209D-03

At iterate  433    f=  2.80230D-01    |proj g|=  2.91562D-03

At iterate  434    f=  2.80229D-01    |proj g|=  5.22634D-03

At iterate  435    f=  2.80229D-01    |proj g|=  1.24017D-03

At iterate  436    f=  2.80229D-01    |proj g|=  1.00940D-03

At iterate  437    f=  2.80229D-01    |proj g|=  3.15134D-03

At iterate  438    f=  2.80229D-01    |proj g|=  1.15576D-03

At iterate  439    f=  2.80228D-01    |proj g|=  7.32985D-04

At iterate  440    f=  2.80227D-01    |proj g|=  4.78313D-03

At iterate  441    f=  2.80226D-01    |proj g|=  8.09033D-03

At iterate  442    f=  2.80225D-01    |proj g|=  1.64673D-03

At iterate  443    f=  2.80224D-01    |proj g|=  1.16255D-02

At iterate  444    f=  2.80223D-01    |proj g|=  3.95273D-03

At iterate  445    f=  2.80223D-01    |proj g|=  9.35537D-04

At iterate  446    f=  2.80223D-01    |proj g|=  8.71743D-04

At iterate  447    f=  2.80223D-01    |proj g|=  1.94951D-03

At iterate  448    f=  2.80223D-01    |proj g|=  2.76409D-04

At iterate  449    f=  2.80223D-01    |proj g|=  2.81772D-04

At iterate  450    f=  2.80223D-01    |proj g|=  1.32738D-03

At iterate  451    f=  2.80222D-01    |proj g|=  4.59627D-03

At iterate  452    f=  2.80221D-01    |proj g|=  4.79647D-03

At iterate  453    f=  2.80218D-01    |proj g|=  1.59622D-02

At iterate  454    f=  2.80216D-01    |proj g|=  6.37746D-03

At iterate  455    f=  2.80215D-01    |proj g|=  4.69760D-03

At iterate  456    f=  2.80214D-01    |proj g|=  2.21711D-03

At iterate  457    f=  2.80214D-01    |proj g|=  1.85380D-03

At iterate  458    f=  2.80214D-01    |proj g|=  1.13722D-03

At iterate  459    f=  2.80214D-01    |proj g|=  3.72898D-03

At iterate  460    f=  2.80214D-01    |proj g|=  3.46115D-03

At iterate  461    f=  2.80213D-01    |proj g|=  3.93590D-03

At iterate  462    f=  2.80211D-01    |proj g|=  2.33551D-03

At iterate  463    f=  2.80211D-01    |proj g|=  1.05539D-03

At iterate  464    f=  2.80210D-01    |proj g|=  5.75467D-04

At iterate  465    f=  2.80209D-01    |proj g|=  8.15834D-04

At iterate  466    f=  2.80206D-01    |proj g|=  1.32830D-03

At iterate  467    f=  2.80206D-01    |proj g|=  6.08908D-03

At iterate  468    f=  2.80203D-01    |proj g|=  4.60341D-03

At iterate  469    f=  2.80199D-01    |proj g|=  1.11373D-03

At iterate  470    f=  2.80198D-01    |proj g|=  5.75576D-03

At iterate  471    f=  2.80197D-01    |proj g|=  3.22293D-04

At iterate  472    f=  2.80196D-01    |proj g|=  5.61927D-04

At iterate  473    f=  2.80196D-01    |proj g|=  2.42656D-03

At iterate  474    f=  2.80196D-01    |proj g|=  1.68376D-03

At iterate  475    f=  2.80196D-01    |proj g|=  7.75730D-04

At iterate  476    f=  2.80195D-01    |proj g|=  6.61768D-04

At iterate  477    f=  2.80194D-01    |proj g|=  1.62286D-03

At iterate  478    f=  2.80193D-01    |proj g|=  4.86205D-03

At iterate  479    f=  2.80192D-01    |proj g|=  9.83835D-03

At iterate  480    f=  2.80191D-01    |proj g|=  3.51956D-03

At iterate  481    f=  2.80190D-01    |proj g|=  9.56987D-04

At iterate  482    f=  2.80189D-01    |proj g|=  1.83495D-03

At iterate  483    f=  2.80189D-01    |proj g|=  4.77648D-03

At iterate  484    f=  2.80189D-01    |proj g|=  1.22777D-03

At iterate  485    f=  2.80189D-01    |proj g|=  8.18661D-04

At iterate  486    f=  2.80188D-01    |proj g|=  3.23830D-03

At iterate  487    f=  2.80188D-01    |proj g|=  2.48662D-03

At iterate  488    f=  2.80188D-01    |proj g|=  3.15370D-03

At iterate  489    f=  2.80188D-01    |proj g|=  1.01700D-03

At iterate  490    f=  2.80188D-01    |proj g|=  1.91699D-03

At iterate  491    f=  2.80188D-01    |proj g|=  8.43055D-03

At iterate  492    f=  2.80188D-01    |proj g|=  5.16838D-03

At iterate  493    f=  2.80187D-01    |proj g|=  4.45449D-04

At iterate  494    f=  2.80187D-01    |proj g|=  6.29126D-03

At iterate  495    f=  2.80186D-01    |proj g|=  8.71188D-03

At iterate  496    f=  2.80185D-01    |proj g|=  3.98011D-03

At iterate  497    f=  2.80185D-01    |proj g|=  5.24970D-04

At iterate  498    f=  2.80185D-01    |proj g|=  2.43333D-03

At iterate  499    f=  2.80185D-01    |proj g|=  3.31179D-03

At iterate  500    f=  2.80185D-01    |proj g|=  5.04860D-03

At iterate  501    f=  2.80185D-01    |proj g|=  6.21574D-03

At iterate  502    f=  2.80184D-01    |proj g|=  9.88492D-03

At iterate  503    f=  2.80184D-01    |proj g|=  3.70563D-03

At iterate  504    f=  2.80184D-01    |proj g|=  1.78268D-03

At iterate  505    f=  2.80184D-01    |proj g|=  9.08645D-04

At iterate  506    f=  2.80184D-01    |proj g|=  1.43096D-03

At iterate  507    f=  2.80183D-01    |proj g|=  2.42101D-03

At iterate  508    f=  2.80183D-01    |proj g|=  4.82726D-04

At iterate  509    f=  2.80183D-01    |proj g|=  3.78774D-03

At iterate  510    f=  2.80183D-01    |proj g|=  6.66804D-04

At iterate  511    f=  2.80183D-01    |proj g|=  1.13954D-03

At iterate  512    f=  2.80183D-01    |proj g|=  2.21837D-03

At iterate  513    f=  2.80183D-01    |proj g|=  2.42540D-03

At iterate  514    f=  2.80182D-01    |proj g|=  1.04240D-02

At iterate  515    f=  2.80182D-01    |proj g|=  6.42519D-03

At iterate  516    f=  2.80182D-01    |proj g|=  5.33603D-04

At iterate  517    f=  2.80182D-01    |proj g|=  7.08141D-04

At iterate  518    f=  2.80182D-01    |proj g|=  9.50055D-04

At iterate  519    f=  2.80181D-01    |proj g|=  2.04048D-03

At iterate  520    f=  2.80181D-01    |proj g|=  3.26140D-03

At iterate  521    f=  2.80181D-01    |proj g|=  1.04940D-03

At iterate  522    f=  2.80181D-01    |proj g|=  4.19815D-03

At iterate  523    f=  2.80180D-01    |proj g|=  2.66877D-03

At iterate  524    f=  2.80180D-01    |proj g|=  1.00443D-03

At iterate  525    f=  2.80180D-01    |proj g|=  2.98786D-03

At iterate  526    f=  2.80180D-01    |proj g|=  1.68844D-03

At iterate  527    f=  2.80180D-01    |proj g|=  4.47401D-03

At iterate  528    f=  2.80180D-01    |proj g|=  1.40173D-03

At iterate  529    f=  2.80180D-01    |proj g|=  8.78472D-04

At iterate  530    f=  2.80179D-01    |proj g|=  1.76563D-03

At iterate  531    f=  2.80179D-01    |proj g|=  1.98456D-03

At iterate  532    f=  2.80179D-01    |proj g|=  2.47381D-03

At iterate  533    f=  2.80179D-01    |proj g|=  6.93373D-04

At iterate  534    f=  2.80179D-01    |proj g|=  1.10106D-03

At iterate  535    f=  2.80179D-01    |proj g|=  2.70207D-03

At iterate  536    f=  2.80179D-01    |proj g|=  4.88065D-03

At iterate  537    f=  2.80179D-01    |proj g|=  6.75228D-03

At iterate  538    f=  2.80178D-01    |proj g|=  4.74716D-03

At iterate  539    f=  2.80178D-01    |proj g|=  8.83214D-03

At iterate  540    f=  2.80178D-01    |proj g|=  3.55981D-03

At iterate  541    f=  2.80178D-01    |proj g|=  1.00689D-03

At iterate  542    f=  2.80177D-01    |proj g|=  2.14114D-03

At iterate  543    f=  2.80177D-01    |proj g|=  2.90917D-03

At iterate  544    f=  2.80177D-01    |proj g|=  4.50962D-03

At iterate  545    f=  2.80176D-01    |proj g|=  3.40126D-03

At iterate  546    f=  2.80176D-01    |proj g|=  7.63828D-03

At iterate  547    f=  2.80175D-01    |proj g|=  5.49343D-03

At iterate  548    f=  2.80175D-01    |proj g|=  2.40713D-03

At iterate  549    f=  2.80175D-01    |proj g|=  4.59645D-04

At iterate  550    f=  2.80175D-01    |proj g|=  1.26228D-04

At iterate  551    f=  2.80175D-01    |proj g|=  1.07919D-03

At iterate  552    f=  2.80175D-01    |proj g|=  1.83537D-03

At iterate  553    f=  2.80174D-01    |proj g|=  2.21177D-03

At iterate  554    f=  2.80174D-01    |proj g|=  4.45803D-04

At iterate  555    f=  2.80174D-01    |proj g|=  4.53457D-04

At iterate  556    f=  2.80174D-01    |proj g|=  3.68441D-03

At iterate  557    f=  2.80174D-01    |proj g|=  8.01233D-04

At iterate  558    f=  2.80174D-01    |proj g|=  4.89422D-04

At iterate  559    f=  2.80174D-01    |proj g|=  3.37483D-04

At iterate  560    f=  2.80174D-01    |proj g|=  1.76983D-03

At iterate  561    f=  2.80174D-01    |proj g|=  8.70298D-04

At iterate  562    f=  2.80174D-01    |proj g|=  1.98532D-04

At iterate  563    f=  2.80174D-01    |proj g|=  7.30655D-04

At iterate  564    f=  2.80174D-01    |proj g|=  1.45000D-03

At iterate  565    f=  2.80173D-01    |proj g|=  1.02397D-03

At iterate  566    f=  2.80173D-01    |proj g|=  2.78455D-03

At iterate  567    f=  2.80173D-01    |proj g|=  1.30960D-03

At iterate  568    f=  2.80173D-01    |proj g|=  1.05094D-03

At iterate  569    f=  2.80173D-01    |proj g|=  2.50608D-04

At iterate  570    f=  2.80173D-01    |proj g|=  1.74401D-04

At iterate  571    f=  2.80173D-01    |proj g|=  1.58244D-03

At iterate  572    f=  2.80173D-01    |proj g|=  1.25376D-03

At iterate  573    f=  2.80173D-01    |proj g|=  6.78213D-04

At iterate  574    f=  2.80173D-01    |proj g|=  3.38429D-04

At iterate  575    f=  2.80173D-01    |proj g|=  1.15800D-03

At iterate  576    f=  2.80172D-01    |proj g|=  2.53433D-03

At iterate  577    f=  2.80172D-01    |proj g|=  3.51305D-03

At iterate  578    f=  2.80172D-01    |proj g|=  7.36105D-04

At iterate  579    f=  2.80171D-01    |proj g|=  1.77393D-03

At iterate  580    f=  2.80171D-01    |proj g|=  6.60898D-04

At iterate  581    f=  2.80171D-01    |proj g|=  5.66685D-04

At iterate  582    f=  2.80171D-01    |proj g|=  1.80708D-03

At iterate  583    f=  2.80171D-01    |proj g|=  1.24898D-03

At iterate  584    f=  2.80171D-01    |proj g|=  4.00304D-04

At iterate  585    f=  2.80171D-01    |proj g|=  3.92504D-04

At iterate  586    f=  2.80171D-01    |proj g|=  5.71813D-04

At iterate  587    f=  2.80171D-01    |proj g|=  8.43634D-04

At iterate  588    f=  2.80171D-01    |proj g|=  4.61954D-04

At iterate  589    f=  2.80171D-01    |proj g|=  1.61660D-03

At iterate  590    f=  2.80171D-01    |proj g|=  3.70790D-04

At iterate  591    f=  2.80171D-01    |proj g|=  7.90219D-04

At iterate  592    f=  2.80170D-01    |proj g|=  2.51636D-03

At iterate  593    f=  2.80170D-01    |proj g|=  5.56821D-04

At iterate  594    f=  2.80170D-01    |proj g|=  4.60717D-03

At iterate  595    f=  2.80170D-01    |proj g|=  8.73307D-04

At iterate  596    f=  2.80170D-01    |proj g|=  6.80166D-04

At iterate  597    f=  2.80170D-01    |proj g|=  7.16614D-04

At iterate  598    f=  2.80170D-01    |proj g|=  1.14793D-03

At iterate  599    f=  2.80170D-01    |proj g|=  1.55226D-03

At iterate  600    f=  2.80170D-01    |proj g|=  3.05380D-04

At iterate  601    f=  2.80170D-01    |proj g|=  1.43869D-04

At iterate  602    f=  2.80169D-01    |proj g|=  1.71251D-03

At iterate  603    f=  2.80169D-01    |proj g|=  2.48797D-03

At iterate  604    f=  2.80169D-01    |proj g|=  4.81694D-03

At iterate  605    f=  2.80169D-01    |proj g|=  2.51419D-03

At iterate  606    f=  2.80169D-01    |proj g|=  7.14723D-04

At iterate  607    f=  2.80168D-01    |proj g|=  2.93305D-03

At iterate  608    f=  2.80168D-01    |proj g|=  2.71175D-03

At iterate  609    f=  2.80168D-01    |proj g|=  3.20769D-03

At iterate  610    f=  2.80168D-01    |proj g|=  1.10639D-03

At iterate  611    f=  2.80168D-01    |proj g|=  1.38997D-03

At iterate  612    f=  2.80168D-01    |proj g|=  2.23309D-03

At iterate  613    f=  2.80168D-01    |proj g|=  1.53013D-03

At iterate  614    f=  2.80168D-01    |proj g|=  3.79672D-04

At iterate  615    f=  2.80168D-01    |proj g|=  6.22399D-04

At iterate  616    f=  2.80168D-01    |proj g|=  3.23335D-04

At iterate  617    f=  2.80167D-01    |proj g|=  6.89412D-04

At iterate  618    f=  2.80167D-01    |proj g|=  3.03673D-03

At iterate  619    f=  2.80167D-01    |proj g|=  2.56942D-03

At iterate  620    f=  2.80167D-01    |proj g|=  7.96178D-04

At iterate  621    f=  2.80167D-01    |proj g|=  1.83911D-04

At iterate  622    f=  2.80167D-01    |proj g|=  3.40439D-04

At iterate  623    f=  2.80167D-01    |proj g|=  4.54859D-04

At iterate  624    f=  2.80167D-01    |proj g|=  1.39745D-03

At iterate  625    f=  2.80167D-01    |proj g|=  3.07120D-04

At iterate  626    f=  2.80167D-01    |proj g|=  1.68288D-04

At iterate  627    f=  2.80167D-01    |proj g|=  1.78404D-04

At iterate  628    f=  2.80167D-01    |proj g|=  5.49462D-04

At iterate  629    f=  2.80167D-01    |proj g|=  7.68850D-05

At iterate  630    f=  2.80167D-01    |proj g|=  8.69459D-04

At iterate  631    f=  2.80167D-01    |proj g|=  2.60713D-04

At iterate  632    f=  2.80167D-01    |proj g|=  4.68934D-04

At iterate  633    f=  2.80167D-01    |proj g|=  8.75903D-04

At iterate  634    f=  2.80167D-01    |proj g|=  1.11579D-03

At iterate  635    f=  2.80167D-01    |proj g|=  3.67402D-04

At iterate  636    f=  2.80167D-01    |proj g|=  2.02096D-03

At iterate  637    f=  2.80167D-01    |proj g|=  2.87354D-04

At iterate  638    f=  2.80167D-01    |proj g|=  4.04267D-04

At iterate  639    f=  2.80167D-01    |proj g|=  7.11671D-04

At iterate  640    f=  2.80167D-01    |proj g|=  8.42498D-04

At iterate  641    f=  2.80167D-01    |proj g|=  2.00518D-03

At iterate  642    f=  2.80167D-01    |proj g|=  6.16057D-04

At iterate  643    f=  2.80167D-01    |proj g|=  1.57171D-04

At iterate  644    f=  2.80167D-01    |proj g|=  3.27085D-04

At iterate  645    f=  2.80167D-01    |proj g|=  6.66360D-04

At iterate  646    f=  2.80167D-01    |proj g|=  1.00716D-03

At iterate  647    f=  2.80167D-01    |proj g|=  3.33112D-04

At iterate  648    f=  2.80167D-01    |proj g|=  1.46526D-03

At iterate  649    f=  2.80167D-01    |proj g|=  3.11443D-04

At iterate  650    f=  2.80167D-01    |proj g|=  6.37446D-04

At iterate  651    f=  2.80167D-01    |proj g|=  9.78370D-04

At iterate  652    f=  2.80167D-01    |proj g|=  1.25845D-03

At iterate  653    f=  2.80167D-01    |proj g|=  6.99770D-04

At iterate  654    f=  2.80167D-01    |proj g|=  2.17212D-04

At iterate  655    f=  2.80167D-01    |proj g|=  3.36213D-04

At iterate  656    f=  2.80167D-01    |proj g|=  1.27330D-03

At iterate  657    f=  2.80167D-01    |proj g|=  1.49521D-03

At iterate  658    f=  2.80166D-01    |proj g|=  1.04914D-03

At iterate  659    f=  2.80166D-01    |proj g|=  4.62519D-03

At iterate  660    f=  2.80166D-01    |proj g|=  2.56204D-03

At iterate  661    f=  2.80166D-01    |proj g|=  3.47976D-04

At iterate  662    f=  2.80166D-01    |proj g|=  5.16679D-05

At iterate  663    f=  2.80166D-01    |proj g|=  1.27727D-04

At iterate  664    f=  2.80166D-01    |proj g|=  4.69331D-04

At iterate  665    f=  2.80166D-01    |proj g|=  2.06335D-04

At iterate  666    f=  2.80166D-01    |proj g|=  1.19006D-04

At iterate  667    f=  2.80166D-01    |proj g|=  1.02354D-04

At iterate  668    f=  2.80166D-01    |proj g|=  5.10453D-04

At iterate  669    f=  2.80166D-01    |proj g|=  5.60202D-04

At iterate  670    f=  2.80166D-01    |proj g|=  2.90077D-03

At iterate  671    f=  2.80166D-01    |proj g|=  1.39139D-03

At iterate  672    f=  2.80165D-01    |proj g|=  4.24854D-04

At iterate  673    f=  2.80165D-01    |proj g|=  6.38921D-04

At iterate  674    f=  2.80165D-01    |proj g|=  7.33263D-04

At iterate  675    f=  2.80165D-01    |proj g|=  1.98165D-03

At iterate  676    f=  2.80165D-01    |proj g|=  1.55762D-03

At iterate  677    f=  2.80165D-01    |proj g|=  1.03512D-03

At iterate  678    f=  2.80165D-01    |proj g|=  8.47018D-04

At iterate  679    f=  2.80164D-01    |proj g|=  1.21749D-03

At iterate  680    f=  2.80164D-01    |proj g|=  3.27718D-03

At iterate  681    f=  2.80164D-01    |proj g|=  5.82638D-03

At iterate  682    f=  2.80163D-01    |proj g|=  1.75996D-03

At iterate  683    f=  2.80163D-01    |proj g|=  2.57261D-04

At iterate  684    f=  2.80163D-01    |proj g|=  5.74554D-04

At iterate  685    f=  2.80163D-01    |proj g|=  5.96243D-04

At iterate  686    f=  2.80163D-01    |proj g|=  2.06871D-03

At iterate  687    f=  2.80163D-01    |proj g|=  1.22122D-03

At iterate  688    f=  2.80163D-01    |proj g|=  3.98342D-04

At iterate  689    f=  2.80163D-01    |proj g|=  1.69775D-04

At iterate  690    f=  2.80163D-01    |proj g|=  3.07945D-04

At iterate  691    f=  2.80163D-01    |proj g|=  7.48300D-04

At iterate  692    f=  2.80163D-01    |proj g|=  1.97647D-03

At iterate  693    f=  2.80163D-01    |proj g|=  1.58876D-03

At iterate  694    f=  2.80162D-01    |proj g|=  1.84105D-03

At iterate  695    f=  2.80162D-01    |proj g|=  2.39496D-03

At iterate  696    f=  2.80162D-01    |proj g|=  7.10773D-04

At iterate  697    f=  2.80162D-01    |proj g|=  4.93105D-04

At iterate  698    f=  2.80162D-01    |proj g|=  2.95769D-03

At iterate  699    f=  2.80162D-01    |proj g|=  2.45453D-03

At iterate  700    f=  2.80162D-01    |proj g|=  5.36794D-03

At iterate  701    f=  2.80162D-01    |proj g|=  3.08228D-03

At iterate  702    f=  2.80162D-01    |proj g|=  4.88398D-04

At iterate  703    f=  2.80162D-01    |proj g|=  3.47304D-04

At iterate  704    f=  2.80162D-01    |proj g|=  5.76900D-04

At iterate  705    f=  2.80161D-01    |proj g|=  7.69958D-04

At iterate  706    f=  2.80161D-01    |proj g|=  1.30786D-03

At iterate  707    f=  2.80161D-01    |proj g|=  1.04056D-03

At iterate  708    f=  2.80161D-01    |proj g|=  6.56258D-04

At iterate  709    f=  2.80161D-01    |proj g|=  1.75616D-03

At iterate  710    f=  2.80161D-01    |proj g|=  1.86225D-03

At iterate  711    f=  2.80161D-01    |proj g|=  3.67252D-04

At iterate  712    f=  2.80161D-01    |proj g|=  5.44313D-04

At iterate  713    f=  2.80161D-01    |proj g|=  3.25400D-03

At iterate  714    f=  2.80161D-01    |proj g|=  2.23050D-03

At iterate  715    f=  2.80161D-01    |proj g|=  6.94945D-04

At iterate  716    f=  2.80161D-01    |proj g|=  5.91068D-04

At iterate  717    f=  2.80160D-01    |proj g|=  1.57544D-03

At iterate  718    f=  2.80160D-01    |proj g|=  1.59591D-03

At iterate  719    f=  2.80160D-01    |proj g|=  2.22012D-03

At iterate  720    f=  2.80160D-01    |proj g|=  3.17065D-04

At iterate  721    f=  2.80160D-01    |proj g|=  1.53315D-04

At iterate  722    f=  2.80160D-01    |proj g|=  4.54730D-04

           * * *

Tit   = total number of iterations
Tnf   = total number of function evaluations
Tnint = total number of segments explored during Cauchy searches
Skip  = number of BFGS updates skipped
Nact  = number of active bounds at final generalized Cauchy point
Projg = norm of the final projected gradient
F     = final function value

           * * *

   N    Tit     Tnf  Tnint  Skip  Nact     Projg        F
   28    722    833      1     0     0   4.547D-04   2.802D-01
  F =  0.28016013029761216

CONVERGENCE: REL_REDUCTION_OF_F_<=_FACTR*EPSMCH
                           Logit Regression Results
==============================================================================
Dep. Variable:                      y   No. Observations:                29813
Model:                          Logit   Df Residuals:                    29785
Method:                           MLE   Df Model:                           27
Date:                Mon, 26 Oct 2026   Pseudo R-squ.:                  0.1901
Time:                        18:04:19   Log-Likelihood:                -8352.4
converged:                       True   LL-Null:                       -10313.
Covariance Type:            nonrobust   LLR p-value:                     0.000
=============================================================================================
                                coef    std err          z      P>|z|      [0.025      0.975]
---------------------------------------------------------------------------------------------
const                        -3.0688      0.196    -15.674      0.000      -3.453      -2.685
dist_goal_line               -0.0638      0.005    -12.885      0.000      -0.074      -0.054
lateral_offset               -0.0798      0.007    -11.484      0.000      -0.093      -0.066
angle_to_goal                 1.9023      0.109     17.526      0.000       1.690       2.115
is_home                      -0.0623      0.041     -1.501      0.133      -0.144       0.019
minute                        0.0015      0.001      1.902      0.057   -4.46e-05       0.003
score_diff                    0.1018      0.016      6.399      0.000       0.071       0.133
is_assisted                  -0.0924      0.089     -1.042      0.298      -0.266       0.081
is_penalty                    2.4086      0.224     10.743      0.000       1.969       2.848
is_open_play                  0.3662      0.096      3.801      0.000       0.177       0.555
from_corner                  -0.1692      0.106     -1.599      0.110      -0.377       0.038
left_foot                     0.5667      0.083      6.857      0.000       0.405       0.729
other_body_part              -0.1454      0.287     -0.506      0.613      -0.709       0.418
right_foot                    0.6009      0.080      7.518      0.000       0.444       0.758
last_action_aerial           -0.4046      0.136     -2.980      0.003      -0.671      -0.139
last_action_ball_recovery     1.1729      0.142      8.267      0.000       0.895       1.451
last_action_ball_touch        0.2693      0.170      1.584      0.113      -0.064       0.603
last_action_chipped           0.4802      0.138      3.471      0.001       0.209       0.751
last_action_cross             0.2435      0.118      2.067      0.039       0.013       0.474
last_action_dispossessed      0.2604      0.329      0.791      0.429      -0.385       0.906
last_action_head_pass         0.4313      0.157      2.755      0.006       0.125       0.738
last_action_lay_off          -0.2253      0.550     -0.410      0.682      -1.303       0.852
last_action_pass              0.6137      0.112      5.495      0.000       0.395       0.833
last_action_rebound           0.5512      0.101      5.453      0.000       0.353       0.749
last_action_standard          1.2224      0.194      6.286      0.000       0.841       1.603
last_action_tackle            0.5968      0.498      1.199      0.231      -0.379       1.573
last_action_take_on           0.9142      0.123      7.421      0.000       0.673       1.156
last_action_throughball       1.4341      0.141     10.205      0.000       1.159       1.710
=============================================================================================

Converged: True

In [5]:

# 5. Fit the full logistic regression model

X_train_full = sm.add_constant(
    train[FULL_FEATURES],
    has_constant="add"
)

y_train = train["result"].to_numpy()

full_fit = sm.Logit(
    y_train,
    X_train_full
).fit(method="lbfgs", maxiter=1000)

print(full_fit.summary())
print("\nConverged:", full_fit.mle_retvals["converged"])

RUNNING THE L-BFGS-B CODE

           * * *

Machine precision = 2.220D-16
 N =           28     M =           10

At X0         0 variables are exactly at the bounds

At iterate    0    f=  6.93147D-01    |proj g|=  1.88477D+01

At iterate    1    f=  4.89100D-01    |proj g|=  4.22737D+00

At iterate    2    f=  4.39995D-01    |proj g|=  3.59864D+00

At iterate    3    f=  3.78370D-01    |proj g|=  1.43259D+00

At iterate    4    f=  3.63823D-01    |proj g|=  1.04063D+00

At iterate    5    f=  3.52397D-01    |proj g|=  1.10438D+00

At iterate    6    f=  3.24472D-01    |proj g|=  1.16503D+00

At iterate    7    f=  3.15309D-01    |proj g|=  1.53850D-01

At iterate    8    f=  3.13283D-01    |proj g|=  8.75863D-02

At iterate    9    f=  3.12322D-01    |proj g|=  7.54453D-02

At iterate   10    f=  3.09989D-01    |proj g|=  6.11176D-02

At iterate   11    f=  3.09211D-01    |proj g|=  3.06904D-02

At iterate   12    f=  3.08780D-01    |proj g|=  1.87649D-02

At iterate   13    f=  3.06682D-01    |proj g|=  1.64350D-01

At iterate   14    f=  3.04531D-01    |proj g|=  2.04866D-01

At iterate   15    f=  3.02174D-01    |proj g|=  4.02821D-01

At iterate   16    f=  3.01019D-01    |proj g|=  2.59206D-01

At iterate   17    f=  3.00727D-01    |proj g|=  2.63817D-02

At iterate   18    f=  3.00668D-01    |proj g|=  4.88220D-02

At iterate   19    f=  3.00633D-01    |proj g|=  5.60864D-02

At iterate   20    f=  3.00324D-01    |proj g|=  7.53696D-02

At iterate   21    f=  2.99553D-01    |proj g|=  1.13414D-01

At iterate   22    f=  2.97790D-01    |proj g|=  1.85414D-01

At iterate   23    f=  2.95702D-01    |proj g|=  1.49337D-01

At iterate   24    f=  2.93943D-01    |proj g|=  3.95059D-01

At iterate   25    f=  2.92682D-01    |proj g|=  1.03811D-01

At iterate   26    f=  2.92437D-01    |proj g|=  5.44013D-03

At iterate   27    f=  2.92411D-01    |proj g|=  1.48701D-02

At iterate   28    f=  2.92327D-01    |proj g|=  8.09082D-02

At iterate   29    f=  2.92292D-01    |proj g|=  1.05042D-01

At iterate   30    f=  2.92213D-01    |proj g|=  1.88335D-02

At iterate   31    f=  2.92172D-01    |proj g|=  2.72403D-02

At iterate   32    f=  2.92052D-01    |proj g|=  3.84262D-02

At iterate   33    f=  2.91669D-01    |proj g|=  6.41398D-02

At iterate   34    f=  2.90742D-01    |proj g|=  9.93476D-02

At iterate   35    f=  2.90030D-01    |proj g|=  3.39645D-02

At iterate   36    f=  2.89628D-01    |proj g|=  5.43478D-02

At iterate   37    f=  2.89215D-01    |proj g|=  1.69632D-01

At iterate   38    f=  2.88476D-01    |proj g|=  7.14459D-02

At iterate   39    f=  2.88118D-01    |proj g|=  2.79851D-02

At iterate   40    f=  2.87930D-01    |proj g|=  1.35905D-01

At iterate   41    f=  2.87758D-01    |proj g|=  1.15344D-01

At iterate   42    f=  2.87620D-01    |proj g|=  3.50754D-02

At iterate   43    f=  2.87475D-01    |proj g|=  4.61971D-02

At iterate   44    f=  2.87455D-01    |proj g|=  2.30217D-02

At iterate   45    f=  2.87448D-01    |proj g|=  5.05042D-03

At iterate   46    f=  2.87445D-01    |proj g|=  1.39607D-02

At iterate   47    f=  2.87439D-01    |proj g|=  3.09741D-02

At iterate   48    f=  2.87424D-01    |proj g|=  5.48646D-02

At iterate   49    f=  2.87389D-01    |proj g|=  8.33146D-02

At iterate   50    f=  2.87316D-01    |proj g|=  1.02918D-01

At iterate   51    f=  2.87203D-01    |proj g|=  1.48104D-01

At iterate   52    f=  2.87168D-01    |proj g|=  4.10513D-02

At iterate   53    f=  2.87104D-01    |proj g|=  2.14717D-02

 This problem is unconstrained.

At iterate   54    f=  2.87054D-01    |proj g|=  1.47032D-02

At iterate   55    f=  2.87040D-01    |proj g|=  2.45042D-02

At iterate   56    f=  2.86937D-01    |proj g|=  6.45501D-02

At iterate   57    f=  2.86802D-01    |proj g|=  5.43327D-02

At iterate   58    f=  2.86636D-01    |proj g|=  3.71218D-02

At iterate   59    f=  2.86557D-01    |proj g|=  1.45792D-02

At iterate   60    f=  2.86492D-01    |proj g|=  1.27802D-02

At iterate   61    f=  2.86427D-01    |proj g|=  7.40334D-02

At iterate   62    f=  2.86319D-01    |proj g|=  4.14816D-02

At iterate   63    f=  2.86123D-01    |proj g|=  1.58708D-01

At iterate   64    f=  2.85943D-01    |proj g|=  2.81655D-01

At iterate   65    f=  2.85567D-01    |proj g|=  7.54326D-02

At iterate   66    f=  2.85268D-01    |proj g|=  4.54750D-02

At iterate   67    f=  2.85204D-01    |proj g|=  2.91606D-02

At iterate   68    f=  2.85200D-01    |proj g|=  3.13646D-02

At iterate   69    f=  2.85177D-01    |proj g|=  4.15713D-02

At iterate   70    f=  2.85159D-01    |proj g|=  4.54581D-02

At iterate   71    f=  2.85079D-01    |proj g|=  5.13257D-02

At iterate   72    f=  2.84927D-01    |proj g|=  4.93551D-02

At iterate   73    f=  2.84912D-01    |proj g|=  6.06492D-02

At iterate   74    f=  2.84830D-01    |proj g|=  1.32158D-02

At iterate   75    f=  2.84682D-01    |proj g|=  2.63518D-02

At iterate   76    f=  2.84573D-01    |proj g|=  1.16533D-01

At iterate   77    f=  2.84458D-01    |proj g|=  3.33686D-02

At iterate   78    f=  2.84415D-01    |proj g|=  5.92041D-03

At iterate   79    f=  2.84329D-01    |proj g|=  3.67346D-02

At iterate   80    f=  2.84258D-01    |proj g|=  1.09374D-02

At iterate   81    f=  2.84195D-01    |proj g|=  8.28946D-02

At iterate   82    f=  2.84120D-01    |proj g|=  5.02719D-02

At iterate   83    f=  2.84052D-01    |proj g|=  4.94049D-03

At iterate   84    f=  2.84050D-01    |proj g|=  2.49768D-03

At iterate   85    f=  2.84046D-01    |proj g|=  2.52664D-03

At iterate   86    f=  2.84044D-01    |proj g|=  1.10232D-02

At iterate   87    f=  2.84041D-01    |proj g|=  7.28401D-03

At iterate   88    f=  2.84030D-01    |proj g|=  2.18097D-02

At iterate   89    f=  2.84015D-01    |proj g|=  2.66282D-02

At iterate   90    f=  2.83990D-01    |proj g|=  2.33612D-02

At iterate   91    f=  2.83761D-01    |proj g|=  2.25074D-02

At iterate   92    f=  2.83575D-01    |proj g|=  6.76390D-02

At iterate   93    f=  2.83241D-01    |proj g|=  4.71194D-02

At iterate   94    f=  2.83125D-01    |proj g|=  1.35559D-01

At iterate   95    f=  2.82898D-01    |proj g|=  5.62975D-02

At iterate   96    f=  2.82754D-01    |proj g|=  2.55210D-02

At iterate   97    f=  2.82747D-01    |proj g|=  1.06358D-02

At iterate   98    f=  2.82742D-01    |proj g|=  2.88937D-03

At iterate   99    f=  2.82736D-01    |proj g|=  1.33958D-02

At iterate  100    f=  2.82727D-01    |proj g|=  1.44306D-02

At iterate  101    f=  2.82726D-01    |proj g|=  2.93971D-02

At iterate  102    f=  2.82719D-01    |proj g|=  2.01862D-02

At iterate  103    f=  2.82709D-01    |proj g|=  1.12781D-02

At iterate  104    f=  2.82691D-01    |proj g|=  6.53135D-03

At iterate  105    f=  2.82683D-01    |proj g|=  2.56729D-02

At iterate  106    f=  2.82679D-01    |proj g|=  4.34102D-03

At iterate  107    f=  2.82676D-01    |proj g|=  4.74606D-03

At iterate  108    f=  2.82670D-01    |proj g|=  1.63184D-02

At iterate  109    f=  2.82665D-01    |proj g|=  1.33511D-02

At iterate  110    f=  2.82647D-01    |proj g|=  2.59348D-03

At iterate  111    f=  2.82638D-01    |proj g|=  5.41636D-03

At iterate  112    f=  2.82626D-01    |proj g|=  2.61370D-02

At iterate  113    f=  2.82602D-01    |proj g|=  1.17445D-02

At iterate  114    f=  2.82566D-01    |proj g|=  1.20157D-02

At iterate  115    f=  2.82511D-01    |proj g|=  1.80616D-01

At iterate  116    f=  2.82157D-01    |proj g|=  2.26031D-02

At iterate  117    f=  2.82008D-01    |proj g|=  4.99897D-02

At iterate  118    f=  2.81869D-01    |proj g|=  2.44513D-02

At iterate  119    f=  2.81865D-01    |proj g|=  4.41549D-02

At iterate  120    f=  2.81851D-01    |proj g|=  1.04966D-02

At iterate  121    f=  2.81848D-01    |proj g|=  4.09302D-03

At iterate  122    f=  2.81846D-01    |proj g|=  5.30786D-03

At iterate  123    f=  2.81844D-01    |proj g|=  1.45046D-02

At iterate  124    f=  2.81842D-01    |proj g|=  5.83546D-03

At iterate  125    f=  2.81841D-01    |proj g|=  8.69543D-03

At iterate  126    f=  2.81838D-01    |proj g|=  1.50078D-02

At iterate  127    f=  2.81834D-01    |proj g|=  1.10672D-02

At iterate  128    f=  2.81831D-01    |proj g|=  1.37495D-02

At iterate  129    f=  2.81822D-01    |proj g|=  3.48546D-02

At iterate  130    f=  2.81814D-01    |proj g|=  2.27249D-02

At iterate  131    f=  2.81800D-01    |proj g|=  8.36449D-03

At iterate  132    f=  2.81775D-01    |proj g|=  1.11766D-02

At iterate  133    f=  2.81730D-01    |proj g|=  2.47467D-02

At iterate  134    f=  2.81660D-01    |proj g|=  4.73371D-02

At iterate  135    f=  2.81649D-01    |proj g|=  1.16577D-02

At iterate  136    f=  2.81589D-01    |proj g|=  2.34134D-02

At iterate  137    f=  2.81568D-01    |proj g|=  1.84936D-02

At iterate  138    f=  2.81551D-01    |proj g|=  6.72842D-03

At iterate  139    f=  2.81541D-01    |proj g|=  1.93833D-02

At iterate  140    f=  2.81527D-01    |proj g|=  2.22852D-02

At iterate  141    f=  2.81497D-01    |proj g|=  3.73167D-02

At iterate  142    f=  2.81475D-01    |proj g|=  1.21413D-02

At iterate  143    f=  2.81457D-01    |proj g|=  1.17961D-02

At iterate  144    f=  2.81434D-01    |proj g|=  3.35969D-02

At iterate  145    f=  2.81393D-01    |proj g|=  1.22240D-02

At iterate  146    f=  2.81344D-01    |proj g|=  2.04832D-02

At iterate  147    f=  2.81340D-01    |proj g|=  5.30014D-03

At iterate  148    f=  2.81333D-01    |proj g|=  5.23014D-03

At iterate  149    f=  2.81331D-01    |proj g|=  2.65934D-03

At iterate  150    f=  2.81327D-01    |proj g|=  6.59815D-03

At iterate  151    f=  2.81321D-01    |proj g|=  1.38415D-02

At iterate  152    f=  2.81307D-01    |proj g|=  2.33078D-02

At iterate  153    f=  2.81284D-01    |proj g|=  3.23407D-02

At iterate  154    f=  2.81277D-01    |proj g|=  1.29697D-02

At iterate  155    f=  2.81257D-01    |proj g|=  2.01735D-02

At iterate  156    f=  2.81247D-01    |proj g|=  3.93342D-03

At iterate  157    f=  2.81245D-01    |proj g|=  1.69849D-03

At iterate  158    f=  2.81244D-01    |proj g|=  7.41538D-03

At iterate  159    f=  2.81241D-01    |proj g|=  9.62137D-03

At iterate  160    f=  2.81238D-01    |proj g|=  2.43619D-02

At iterate  161    f=  2.81233D-01    |proj g|=  1.19639D-02

At iterate  162    f=  2.81229D-01    |proj g|=  4.76522D-03

At iterate  163    f=  2.81225D-01    |proj g|=  1.18940D-02

At iterate  164    f=  2.81219D-01    |proj g|=  2.06289D-02

At iterate  165    f=  2.81211D-01    |proj g|=  1.30637D-02

At iterate  166    f=  2.81210D-01    |proj g|=  2.72345D-02

At iterate  167    f=  2.81206D-01    |proj g|=  7.54545D-03

At iterate  168    f=  2.81205D-01    |proj g|=  2.51293D-03

At iterate  169    f=  2.81205D-01    |proj g|=  3.26649D-03

At iterate  170    f=  2.81203D-01    |proj g|=  5.90022D-03

At iterate  171    f=  2.81202D-01    |proj g|=  3.59650D-03

At iterate  172    f=  2.81202D-01    |proj g|=  2.36400D-03

At iterate  173    f=  2.81200D-01    |proj g|=  2.63415D-03

At iterate  174    f=  2.81197D-01    |proj g|=  9.86571D-03

At iterate  175    f=  2.81187D-01    |proj g|=  1.01105D-02

At iterate  176    f=  2.81157D-01    |proj g|=  7.21969D-03

At iterate  177    f=  2.81115D-01    |proj g|=  2.57866D-02

At iterate  178    f=  2.81103D-01    |proj g|=  3.16060D-02

At iterate  179    f=  2.81076D-01    |proj g|=  1.95572D-02

At iterate  180    f=  2.81058D-01    |proj g|=  1.33704D-02

At iterate  181    f=  2.81054D-01    |proj g|=  1.68422D-03

At iterate  182    f=  2.81052D-01    |proj g|=  2.24860D-03

At iterate  183    f=  2.81047D-01    |proj g|=  2.11708D-02

At iterate  184    f=  2.81037D-01    |proj g|=  1.46358D-02

At iterate  185    f=  2.81027D-01    |proj g|=  4.65036D-03

At iterate  186    f=  2.81022D-01    |proj g|=  3.27669D-03

At iterate  187    f=  2.81018D-01    |proj g|=  2.88052D-03

At iterate  188    f=  2.81017D-01    |proj g|=  1.03859D-02

At iterate  189    f=  2.81014D-01    |proj g|=  1.29881D-02

At iterate  190    f=  2.81011D-01    |proj g|=  9.35001D-03

At iterate  191    f=  2.81006D-01    |proj g|=  3.19397D-02

At iterate  192    f=  2.80996D-01    |proj g|=  7.09674D-03

At iterate  193    f=  2.80984D-01    |proj g|=  7.77326D-03

At iterate  194    f=  2.80942D-01    |proj g|=  4.81565D-02

At iterate  195    f=  2.80887D-01    |proj g|=  7.62497D-02

At iterate  196    f=  2.80808D-01    |proj g|=  7.10574D-02

At iterate  197    f=  2.80802D-01    |proj g|=  9.29745D-02

At iterate  198    f=  2.80739D-01    |proj g|=  4.83041D-02

At iterate  199    f=  2.80710D-01    |proj g|=  1.19494D-02

At iterate  200    f=  2.80702D-01    |proj g|=  2.09269D-02

At iterate  201    f=  2.80698D-01    |proj g|=  1.86740D-02

At iterate  202    f=  2.80697D-01    |proj g|=  2.52344D-02

At iterate  203    f=  2.80694D-01    |proj g|=  1.78175D-03

At iterate  204    f=  2.80694D-01    |proj g|=  1.73477D-03

At iterate  205    f=  2.80693D-01    |proj g|=  2.73154D-03

At iterate  206    f=  2.80690D-01    |proj g|=  7.84204D-03

At iterate  207    f=  2.80686D-01    |proj g|=  1.18371D-02

At iterate  208    f=  2.80679D-01    |proj g|=  1.08712D-02

At iterate  209    f=  2.80670D-01    |proj g|=  2.11785D-02

At iterate  210    f=  2.80665D-01    |proj g|=  7.57501D-03

At iterate  211    f=  2.80655D-01    |proj g|=  4.94135D-03

At iterate  212    f=  2.80632D-01    |proj g|=  1.14879D-02

At iterate  213    f=  2.80616D-01    |proj g|=  9.37312D-03

At iterate  214    f=  2.80615D-01    |proj g|=  2.65748D-02

At iterate  215    f=  2.80596D-01    |proj g|=  1.22345D-02

At iterate  216    f=  2.80586D-01    |proj g|=  7.51924D-03

At iterate  217    f=  2.80579D-01    |proj g|=  5.48324D-03

At iterate  218    f=  2.80574D-01    |proj g|=  4.24699D-03

At iterate  219    f=  2.80569D-01    |proj g|=  2.83246D-03

At iterate  220    f=  2.80567D-01    |proj g|=  3.25918D-03

At iterate  221    f=  2.80566D-01    |proj g|=  3.61253D-03

At iterate  222    f=  2.80564D-01    |proj g|=  8.23864D-03

At iterate  223    f=  2.80563D-01    |proj g|=  1.79366D-03

At iterate  224    f=  2.80562D-01    |proj g|=  3.40701D-03

At iterate  225    f=  2.80561D-01    |proj g|=  1.47768D-03

At iterate  226    f=  2.80561D-01    |proj g|=  9.69879D-03

At iterate  227    f=  2.80560D-01    |proj g|=  2.27059D-03

At iterate  228    f=  2.80559D-01    |proj g|=  2.39822D-03

At iterate  229    f=  2.80558D-01    |proj g|=  5.41406D-03

At iterate  230    f=  2.80556D-01    |proj g|=  5.71430D-03

At iterate  231    f=  2.80554D-01    |proj g|=  6.50110D-03

At iterate  232    f=  2.80553D-01    |proj g|=  1.68131D-02

At iterate  233    f=  2.80551D-01    |proj g|=  7.54844D-03

At iterate  234    f=  2.80549D-01    |proj g|=  1.92227D-03

At iterate  235    f=  2.80549D-01    |proj g|=  4.29432D-03

At iterate  236    f=  2.80548D-01    |proj g|=  4.10402D-03

At iterate  237    f=  2.80548D-01    |proj g|=  8.42950D-03

At iterate  238    f=  2.80548D-01    |proj g|=  4.99137D-03

At iterate  239    f=  2.80548D-01    |proj g|=  8.18707D-04

At iterate  240    f=  2.80547D-01    |proj g|=  2.06134D-03

At iterate  241    f=  2.80547D-01    |proj g|=  5.59626D-03

At iterate  242    f=  2.80547D-01    |proj g|=  9.60288D-03

At iterate  243    f=  2.80545D-01    |proj g|=  1.50367D-02

At iterate  244    f=  2.80542D-01    |proj g|=  1.84380D-02

At iterate  245    f=  2.80539D-01    |proj g|=  1.33196D-02

At iterate  246    f=  2.80538D-01    |proj g|=  1.81591D-02

At iterate  247    f=  2.80534D-01    |proj g|=  4.90270D-03

At iterate  248    f=  2.80532D-01    |proj g|=  7.09520D-03

At iterate  249    f=  2.80530D-01    |proj g|=  2.00413D-02

At iterate  250    f=  2.80527D-01    |proj g|=  4.71692D-03

At iterate  251    f=  2.80525D-01    |proj g|=  8.86463D-03

At iterate  252    f=  2.80523D-01    |proj g|=  1.92345D-03

At iterate  253    f=  2.80522D-01    |proj g|=  1.29701D-03

At iterate  254    f=  2.80519D-01    |proj g|=  3.74034D-03

At iterate  255    f=  2.80517D-01    |proj g|=  8.49131D-03

At iterate  256    f=  2.80508D-01    |proj g|=  1.48718D-02

At iterate  257    f=  2.80501D-01    |proj g|=  1.07452D-02

At iterate  258    f=  2.80499D-01    |proj g|=  2.42647D-02

At iterate  259    f=  2.80494D-01    |proj g|=  6.83564D-03

At iterate  260    f=  2.80493D-01    |proj g|=  2.77655D-03

At iterate  261    f=  2.80493D-01    |proj g|=  3.94195D-03

At iterate  262    f=  2.80491D-01    |proj g|=  5.10261D-03

At iterate  263    f=  2.80491D-01    |proj g|=  1.86697D-02

At iterate  264    f=  2.80487D-01    |proj g|=  1.38373D-02

At iterate  265    f=  2.80482D-01    |proj g|=  4.71349D-03

At iterate  266    f=  2.80478D-01    |proj g|=  3.81190D-03

At iterate  267    f=  2.80475D-01    |proj g|=  7.23844D-03

At iterate  268    f=  2.80473D-01    |proj g|=  6.39146D-03

At iterate  269    f=  2.80473D-01    |proj g|=  1.06698D-02

At iterate  270    f=  2.80471D-01    |proj g|=  3.39556D-03

At iterate  271    f=  2.80470D-01    |proj g|=  2.24628D-03

At iterate  272    f=  2.80470D-01    |proj g|=  3.27062D-03

At iterate  273    f=  2.80470D-01    |proj g|=  2.83107D-03

At iterate  274    f=  2.80469D-01    |proj g|=  5.41824D-03

At iterate  275    f=  2.80468D-01    |proj g|=  5.91857D-03

At iterate  276    f=  2.80467D-01    |proj g|=  2.64871D-03

At iterate  277    f=  2.80465D-01    |proj g|=  2.26178D-03

At iterate  278    f=  2.80461D-01    |proj g|=  3.19486D-03

At iterate  279    f=  2.80456D-01    |proj g|=  1.54341D-02

At iterate  280    f=  2.80449D-01    |proj g|=  1.51709D-02

At iterate  281    f=  2.80448D-01    |proj g|=  1.75498D-02

At iterate  282    f=  2.80434D-01    |proj g|=  3.18769D-03

At iterate  283    f=  2.80423D-01    |proj g|=  2.52745D-03

At iterate  284    f=  2.80422D-01    |proj g|=  1.20690D-02

At iterate  285    f=  2.80417D-01    |proj g|=  5.36321D-03

At iterate  286    f=  2.80416D-01    |proj g|=  9.15396D-03

At iterate  287    f=  2.80415D-01    |proj g|=  4.62389D-03

At iterate  288    f=  2.80415D-01    |proj g|=  4.41644D-03

At iterate  289    f=  2.80413D-01    |proj g|=  1.88550D-03

At iterate  290    f=  2.80408D-01    |proj g|=  2.71247D-03

At iterate  291    f=  2.80394D-01    |proj g|=  7.56535D-03

At iterate  292    f=  2.80365D-01    |proj g|=  5.26029D-03

At iterate  293    f=  2.80358D-01    |proj g|=  1.46424D-02

At iterate  294    f=  2.80350D-01    |proj g|=  7.00430D-03

At iterate  295    f=  2.80344D-01    |proj g|=  5.81994D-03

At iterate  296    f=  2.80343D-01    |proj g|=  1.08322D-02

At iterate  297    f=  2.80341D-01    |proj g|=  2.49578D-03

At iterate  298    f=  2.80341D-01    |proj g|=  7.10015D-03

At iterate  299    f=  2.80340D-01    |proj g|=  7.96838D-03

At iterate  300    f=  2.80340D-01    |proj g|=  1.11640D-02

At iterate  301    f=  2.80339D-01    |proj g|=  3.33576D-03

At iterate  302    f=  2.80339D-01    |proj g|=  2.70042D-03

At iterate  303    f=  2.80338D-01    |proj g|=  8.47142D-03

At iterate  304    f=  2.80338D-01    |proj g|=  1.27904D-02

At iterate  305    f=  2.80337D-01    |proj g|=  1.31326D-02

At iterate  306    f=  2.80335D-01    |proj g|=  2.69168D-03

At iterate  307    f=  2.80334D-01    |proj g|=  1.69051D-03

At iterate  308    f=  2.80330D-01    |proj g|=  1.45071D-02

At iterate  309    f=  2.80329D-01    |proj g|=  1.14999D-02

At iterate  310    f=  2.80328D-01    |proj g|=  1.39825D-02

At iterate  311    f=  2.80327D-01    |proj g|=  4.90463D-03

At iterate  312    f=  2.80326D-01    |proj g|=  2.76058D-03

At iterate  313    f=  2.80324D-01    |proj g|=  2.96313D-03

At iterate  314    f=  2.80321D-01    |proj g|=  1.20910D-02

At iterate  315    f=  2.80319D-01    |proj g|=  5.20055D-03

At iterate  316    f=  2.80318D-01    |proj g|=  1.50402D-03

At iterate  317    f=  2.80317D-01    |proj g|=  3.80046D-03

At iterate  318    f=  2.80317D-01    |proj g|=  5.07675D-03

At iterate  319    f=  2.80315D-01    |proj g|=  3.76849D-03

At iterate  320    f=  2.80313D-01    |proj g|=  1.41324D-02

At iterate  321    f=  2.80309D-01    |proj g|=  7.02235D-03

At iterate  322    f=  2.80300D-01    |proj g|=  2.64942D-03

At iterate  323    f=  2.80297D-01    |proj g|=  1.96075D-02

At iterate  324    f=  2.80295D-01    |proj g|=  4.13427D-03

At iterate  325    f=  2.80294D-01    |proj g|=  4.02120D-03

At iterate  326    f=  2.80293D-01    |proj g|=  1.04054D-02

At iterate  327    f=  2.80291D-01    |proj g|=  6.86052D-03

At iterate  328    f=  2.80290D-01    |proj g|=  4.03320D-03

At iterate  329    f=  2.80288D-01    |proj g|=  1.60344D-03

At iterate  330    f=  2.80288D-01    |proj g|=  1.29153D-03

At iterate  331    f=  2.80288D-01    |proj g|=  3.72345D-03

At iterate  332    f=  2.80288D-01    |proj g|=  2.34759D-03

At iterate  333    f=  2.80288D-01    |proj g|=  1.46986D-03

At iterate  334    f=  2.80287D-01    |proj g|=  3.17007D-03

At iterate  335    f=  2.80287D-01    |proj g|=  2.99765D-03

At iterate  336    f=  2.80287D-01    |proj g|=  2.33948D-03

At iterate  337    f=  2.80287D-01    |proj g|=  8.33924D-03

At iterate  338    f=  2.80286D-01    |proj g|=  1.26859D-03

At iterate  339    f=  2.80285D-01    |proj g|=  1.03912D-03

At iterate  340    f=  2.80285D-01    |proj g|=  1.39879D-03

At iterate  341    f=  2.80285D-01    |proj g|=  1.51129D-03

At iterate  342    f=  2.80285D-01    |proj g|=  1.16813D-03

At iterate  343    f=  2.80285D-01    |proj g|=  6.09619D-04

At iterate  344    f=  2.80285D-01    |proj g|=  3.86900D-04

At iterate  345    f=  2.80285D-01    |proj g|=  3.92120D-03

At iterate  346    f=  2.80284D-01    |proj g|=  3.43184D-03

At iterate  347    f=  2.80282D-01    |proj g|=  2.05886D-02

At iterate  348    f=  2.80279D-01    |proj g|=  6.65263D-03

At iterate  349    f=  2.80275D-01    |proj g|=  5.08154D-03

At iterate  350    f=  2.80274D-01    |proj g|=  2.33714D-03

At iterate  351    f=  2.80274D-01    |proj g|=  7.18279D-03

At iterate  352    f=  2.80273D-01    |proj g|=  1.09372D-03

At iterate  353    f=  2.80273D-01    |proj g|=  3.16856D-03

At iterate  354    f=  2.80273D-01    |proj g|=  4.72215D-03

At iterate  355    f=  2.80272D-01    |proj g|=  1.40747D-03

At iterate  356    f=  2.80272D-01    |proj g|=  6.11952D-04

At iterate  357    f=  2.80272D-01    |proj g|=  2.74110D-03

At iterate  358    f=  2.80272D-01    |proj g|=  5.30828D-03

At iterate  359    f=  2.80272D-01    |proj g|=  5.57751D-03

At iterate  360    f=  2.80272D-01    |proj g|=  7.32114D-03

At iterate  361    f=  2.80272D-01    |proj g|=  3.12611D-03

At iterate  362    f=  2.80271D-01    |proj g|=  1.47514D-03

At iterate  363    f=  2.80271D-01    |proj g|=  2.75927D-03

At iterate  364    f=  2.80271D-01    |proj g|=  3.88958D-03

At iterate  365    f=  2.80271D-01    |proj g|=  5.94069D-03

At iterate  366    f=  2.80271D-01    |proj g|=  1.66743D-03

At iterate  367    f=  2.80271D-01    |proj g|=  2.75504D-03

At iterate  368    f=  2.80269D-01    |proj g|=  4.13812D-03

At iterate  369    f=  2.80269D-01    |proj g|=  6.08237D-03

At iterate  370    f=  2.80266D-01    |proj g|=  5.82974D-03

At iterate  371    f=  2.80263D-01    |proj g|=  2.44252D-03

At iterate  372    f=  2.80256D-01    |proj g|=  1.32987D-02

At iterate  373    f=  2.80256D-01    |proj g|=  9.48768D-04

At iterate  374    f=  2.80255D-01    |proj g|=  7.07211D-04

At iterate  375    f=  2.80255D-01    |proj g|=  1.74264D-03

At iterate  376    f=  2.80255D-01    |proj g|=  1.85251D-03

At iterate  377    f=  2.80254D-01    |proj g|=  4.29113D-04

At iterate  378    f=  2.80254D-01    |proj g|=  8.22343D-04

At iterate  379    f=  2.80254D-01    |proj g|=  8.37317D-04

At iterate  380    f=  2.80254D-01    |proj g|=  4.82022D-04

At iterate  381    f=  2.80254D-01    |proj g|=  3.18965D-04

At iterate  382    f=  2.80253D-01    |proj g|=  2.19015D-03

At iterate  383    f=  2.80253D-01    |proj g|=  5.50903D-04

At iterate  384    f=  2.80253D-01    |proj g|=  6.24824D-03

At iterate  385    f=  2.80253D-01    |proj g|=  1.81591D-03

At iterate  386    f=  2.80253D-01    |proj g|=  6.26426D-04

At iterate  387    f=  2.80253D-01    |proj g|=  3.39715D-03

At iterate  388    f=  2.80252D-01    |proj g|=  6.01511D-03

At iterate  389    f=  2.80252D-01    |proj g|=  7.15192D-03

At iterate  390    f=  2.80251D-01    |proj g|=  6.63297D-03

At iterate  391    f=  2.80251D-01    |proj g|=  3.30791D-03

At iterate  392    f=  2.80251D-01    |proj g|=  4.20431D-04

At iterate  393    f=  2.80250D-01    |proj g|=  4.21173D-03

At iterate  394    f=  2.80250D-01    |proj g|=  6.00495D-03

At iterate  395    f=  2.80250D-01    |proj g|=  8.92917D-03

At iterate  396    f=  2.80249D-01    |proj g|=  8.06255D-03

At iterate  397    f=  2.80249D-01    |proj g|=  1.34371D-02

At iterate  398    f=  2.80248D-01    |proj g|=  8.00945D-03

At iterate  399    f=  2.80247D-01    |proj g|=  2.89217D-03

At iterate  400    f=  2.80246D-01    |proj g|=  2.53853D-03

At iterate  401    f=  2.80245D-01    |proj g|=  4.01929D-03

At iterate  402    f=  2.80244D-01    |proj g|=  1.59596D-03

At iterate  403    f=  2.80243D-01    |proj g|=  2.11004D-03

At iterate  404    f=  2.80243D-01    |proj g|=  2.54142D-03

At iterate  405    f=  2.80243D-01    |proj g|=  3.12666D-03

At iterate  406    f=  2.80242D-01    |proj g|=  4.09699D-03

At iterate  407    f=  2.80241D-01    |proj g|=  3.12897D-03

At iterate  408    f=  2.80240D-01    |proj g|=  1.46233D-02

At iterate  409    f=  2.80238D-01    |proj g|=  8.60780D-03

At iterate  410    f=  2.80236D-01    |proj g|=  4.85877D-03

At iterate  411    f=  2.80235D-01    |proj g|=  5.50339D-03

At iterate  412    f=  2.80234D-01    |proj g|=  1.00974D-03

At iterate  413    f=  2.80234D-01    |proj g|=  2.30574D-04

At iterate  414    f=  2.80234D-01    |proj g|=  2.32347D-04

At iterate  415    f=  2.80234D-01    |proj g|=  3.12912D-03

At iterate  416    f=  2.80234D-01    |proj g|=  6.91276D-04

At iterate  417    f=  2.80234D-01    |proj g|=  4.29200D-04

At iterate  418    f=  2.80234D-01    |proj g|=  1.22377D-03

At iterate  419    f=  2.80234D-01    |proj g|=  9.45657D-04

At iterate  420    f=  2.80234D-01    |proj g|=  4.95387D-03

At iterate  421    f=  2.80233D-01    |proj g|=  2.34522D-03

At iterate  422    f=  2.80233D-01    |proj g|=  7.74993D-04

At iterate  423    f=  2.80233D-01    |proj g|=  1.44105D-03

At iterate  424    f=  2.80232D-01    |proj g|=  5.58782D-03

At iterate  425    f=  2.80232D-01    |proj g|=  2.64506D-03

At iterate  426    f=  2.80232D-01    |proj g|=  1.34289D-03

At iterate  427    f=  2.80231D-01    |proj g|=  5.29105D-03

At iterate  428    f=  2.80231D-01    |proj g|=  6.95251D-03

At iterate  429    f=  2.80230D-01    |proj g|=  3.16474D-03

At iterate  430    f=  2.80230D-01    |proj g|=  2.03436D-03

At iterate  431    f=  2.80230D-01    |proj g|=  1.19949D-03

At iterate  432    f=  2.80230D-01    |proj g|=  2.27209D-03

At iterate  433    f=  2.80230D-01    |proj g|=  2.91562D-03

At iterate  434    f=  2.80229D-01    |proj g|=  5.22634D-03

At iterate  435    f=  2.80229D-01    |proj g|=  1.24017D-03

At iterate  436    f=  2.80229D-01    |proj g|=  1.00940D-03

At iterate  437    f=  2.80229D-01    |proj g|=  3.15134D-03

At iterate  438    f=  2.80229D-01    |proj g|=  1.15576D-03

At iterate  439    f=  2.80228D-01    |proj g|=  7.32985D-04

At iterate  440    f=  2.80227D-01    |proj g|=  4.78313D-03

At iterate  441    f=  2.80226D-01    |proj g|=  8.09033D-03

At iterate  442    f=  2.80225D-01    |proj g|=  1.64673D-03

At iterate  443    f=  2.80224D-01    |proj g|=  1.16255D-02

At iterate  444    f=  2.80223D-01    |proj g|=  3.95273D-03

At iterate  445    f=  2.80223D-01    |proj g|=  9.35537D-04

At iterate  446    f=  2.80223D-01    |proj g|=  8.71743D-04

At iterate  447    f=  2.80223D-01    |proj g|=  1.94951D-03

At iterate  448    f=  2.80223D-01    |proj g|=  2.76409D-04

At iterate  449    f=  2.80223D-01    |proj g|=  2.81772D-04

At iterate  450    f=  2.80223D-01    |proj g|=  1.32738D-03

At iterate  451    f=  2.80222D-01    |proj g|=  4.59627D-03

At iterate  452    f=  2.80221D-01    |proj g|=  4.79647D-03

At iterate  453    f=  2.80218D-01    |proj g|=  1.59622D-02

At iterate  454    f=  2.80216D-01    |proj g|=  6.37746D-03

At iterate  455    f=  2.80215D-01    |proj g|=  4.69760D-03

At iterate  456    f=  2.80214D-01    |proj g|=  2.21711D-03

At iterate  457    f=  2.80214D-01    |proj g|=  1.85380D-03

At iterate  458    f=  2.80214D-01    |proj g|=  1.13722D-03

At iterate  459    f=  2.80214D-01    |proj g|=  3.72898D-03

At iterate  460    f=  2.80214D-01    |proj g|=  3.46115D-03

At iterate  461    f=  2.80213D-01    |proj g|=  3.93590D-03

At iterate  462    f=  2.80211D-01    |proj g|=  2.33551D-03

At iterate  463    f=  2.80211D-01    |proj g|=  1.05539D-03

At iterate  464    f=  2.80210D-01    |proj g|=  5.75467D-04

At iterate  465    f=  2.80209D-01    |proj g|=  8.15834D-04

At iterate  466    f=  2.80206D-01    |proj g|=  1.32830D-03

At iterate  467    f=  2.80206D-01    |proj g|=  6.08908D-03

At iterate  468    f=  2.80203D-01    |proj g|=  4.60341D-03

At iterate  469    f=  2.80199D-01    |proj g|=  1.11373D-03

At iterate  470    f=  2.80198D-01    |proj g|=  5.75576D-03

At iterate  471    f=  2.80197D-01    |proj g|=  3.22293D-04

At iterate  472    f=  2.80196D-01    |proj g|=  5.61927D-04

At iterate  473    f=  2.80196D-01    |proj g|=  2.42656D-03

At iterate  474    f=  2.80196D-01    |proj g|=  1.68376D-03

At iterate  475    f=  2.80196D-01    |proj g|=  7.75730D-04

At iterate  476    f=  2.80195D-01    |proj g|=  6.61768D-04

At iterate  477    f=  2.80194D-01    |proj g|=  1.62286D-03

At iterate  478    f=  2.80193D-01    |proj g|=  4.86205D-03

At iterate  479    f=  2.80192D-01    |proj g|=  9.83835D-03

At iterate  480    f=  2.80191D-01    |proj g|=  3.51956D-03

At iterate  481    f=  2.80190D-01    |proj g|=  9.56987D-04

At iterate  482    f=  2.80189D-01    |proj g|=  1.83495D-03

At iterate  483    f=  2.80189D-01    |proj g|=  4.77648D-03

At iterate  484    f=  2.80189D-01    |proj g|=  1.22777D-03

At iterate  485    f=  2.80189D-01    |proj g|=  8.18661D-04

At iterate  486    f=  2.80188D-01    |proj g|=  3.23830D-03

At iterate  487    f=  2.80188D-01    |proj g|=  2.48662D-03

At iterate  488    f=  2.80188D-01    |proj g|=  3.15370D-03

At iterate  489    f=  2.80188D-01    |proj g|=  1.01700D-03

At iterate  490    f=  2.80188D-01    |proj g|=  1.91699D-03

At iterate  491    f=  2.80188D-01    |proj g|=  8.43055D-03

At iterate  492    f=  2.80188D-01    |proj g|=  5.16838D-03

At iterate  493    f=  2.80187D-01    |proj g|=  4.45449D-04

At iterate  494    f=  2.80187D-01    |proj g|=  6.29126D-03

At iterate  495    f=  2.80186D-01    |proj g|=  8.71188D-03

At iterate  496    f=  2.80185D-01    |proj g|=  3.98011D-03

At iterate  497    f=  2.80185D-01    |proj g|=  5.24970D-04

At iterate  498    f=  2.80185D-01    |proj g|=  2.43333D-03

At iterate  499    f=  2.80185D-01    |proj g|=  3.31179D-03

At iterate  500    f=  2.80185D-01    |proj g|=  5.04860D-03

At iterate  501    f=  2.80185D-01    |proj g|=  6.21574D-03

At iterate  502    f=  2.80184D-01    |proj g|=  9.88492D-03

At iterate  503    f=  2.80184D-01    |proj g|=  3.70563D-03

At iterate  504    f=  2.80184D-01    |proj g|=  1.78268D-03

At iterate  505    f=  2.80184D-01    |proj g|=  9.08645D-04

At iterate  506    f=  2.80184D-01    |proj g|=  1.43096D-03

At iterate  507    f=  2.80183D-01    |proj g|=  2.42101D-03

At iterate  508    f=  2.80183D-01    |proj g|=  4.82726D-04

At iterate  509    f=  2.80183D-01    |proj g|=  3.78774D-03

At iterate  510    f=  2.80183D-01    |proj g|=  6.66804D-04

At iterate  511    f=  2.80183D-01    |proj g|=  1.13954D-03

At iterate  512    f=  2.80183D-01    |proj g|=  2.21837D-03

At iterate  513    f=  2.80183D-01    |proj g|=  2.42540D-03

At iterate  514    f=  2.80182D-01    |proj g|=  1.04240D-02

At iterate  515    f=  2.80182D-01    |proj g|=  6.42519D-03

At iterate  516    f=  2.80182D-01    |proj g|=  5.33603D-04

At iterate  517    f=  2.80182D-01    |proj g|=  7.08141D-04

At iterate  518    f=  2.80182D-01    |proj g|=  9.50055D-04

At iterate  519    f=  2.80181D-01    |proj g|=  2.04048D-03

At iterate  520    f=  2.80181D-01    |proj g|=  3.26140D-03

At iterate  521    f=  2.80181D-01    |proj g|=  1.04940D-03

At iterate  522    f=  2.80181D-01    |proj g|=  4.19815D-03

At iterate  523    f=  2.80180D-01    |proj g|=  2.66877D-03

At iterate  524    f=  2.80180D-01    |proj g|=  1.00443D-03

At iterate  525    f=  2.80180D-01    |proj g|=  2.98786D-03

At iterate  526    f=  2.80180D-01    |proj g|=  1.68844D-03

At iterate  527    f=  2.80180D-01    |proj g|=  4.47401D-03

At iterate  528    f=  2.80180D-01    |proj g|=  1.40173D-03

At iterate  529    f=  2.80180D-01    |proj g|=  8.78472D-04

At iterate  530    f=  2.80179D-01    |proj g|=  1.76563D-03

At iterate  531    f=  2.80179D-01    |proj g|=  1.98456D-03

At iterate  532    f=  2.80179D-01    |proj g|=  2.47381D-03

At iterate  533    f=  2.80179D-01    |proj g|=  6.93373D-04

At iterate  534    f=  2.80179D-01    |proj g|=  1.10106D-03

At iterate  535    f=  2.80179D-01    |proj g|=  2.70207D-03

At iterate  536    f=  2.80179D-01    |proj g|=  4.88065D-03

At iterate  537    f=  2.80179D-01    |proj g|=  6.75228D-03

At iterate  538    f=  2.80178D-01    |proj g|=  4.74716D-03

At iterate  539    f=  2.80178D-01    |proj g|=  8.83214D-03

At iterate  540    f=  2.80178D-01    |proj g|=  3.55981D-03

At iterate  541    f=  2.80178D-01    |proj g|=  1.00689D-03

At iterate  542    f=  2.80177D-01    |proj g|=  2.14114D-03

At iterate  543    f=  2.80177D-01    |proj g|=  2.90917D-03

At iterate  544    f=  2.80177D-01    |proj g|=  4.50962D-03

At iterate  545    f=  2.80176D-01    |proj g|=  3.40126D-03

At iterate  546    f=  2.80176D-01    |proj g|=  7.63828D-03

At iterate  547    f=  2.80175D-01    |proj g|=  5.49343D-03

At iterate  548    f=  2.80175D-01    |proj g|=  2.40713D-03

At iterate  549    f=  2.80175D-01    |proj g|=  4.59645D-04

At iterate  550    f=  2.80175D-01    |proj g|=  1.26228D-04

At iterate  551    f=  2.80175D-01    |proj g|=  1.07919D-03

At iterate  552    f=  2.80175D-01    |proj g|=  1.83537D-03

At iterate  553    f=  2.80174D-01    |proj g|=  2.21177D-03

At iterate  554    f=  2.80174D-01    |proj g|=  4.45803D-04

At iterate  555    f=  2.80174D-01    |proj g|=  4.53457D-04

At iterate  556    f=  2.80174D-01    |proj g|=  3.68441D-03

At iterate  557    f=  2.80174D-01    |proj g|=  8.01233D-04

At iterate  558    f=  2.80174D-01    |proj g|=  4.89422D-04

At iterate  559    f=  2.80174D-01    |proj g|=  3.37483D-04

At iterate  560    f=  2.80174D-01    |proj g|=  1.76983D-03

At iterate  561    f=  2.80174D-01    |proj g|=  8.70298D-04

At iterate  562    f=  2.80174D-01    |proj g|=  1.98532D-04

At iterate  563    f=  2.80174D-01    |proj g|=  7.30655D-04

At iterate  564    f=  2.80174D-01    |proj g|=  1.45000D-03

At iterate  565    f=  2.80173D-01    |proj g|=  1.02397D-03

At iterate  566    f=  2.80173D-01    |proj g|=  2.78455D-03

At iterate  567    f=  2.80173D-01    |proj g|=  1.30960D-03

At iterate  568    f=  2.80173D-01    |proj g|=  1.05094D-03

At iterate  569    f=  2.80173D-01    |proj g|=  2.50608D-04

At iterate  570    f=  2.80173D-01    |proj g|=  1.74401D-04

At iterate  571    f=  2.80173D-01    |proj g|=  1.58244D-03

At iterate  572    f=  2.80173D-01    |proj g|=  1.25376D-03

At iterate  573    f=  2.80173D-01    |proj g|=  6.78213D-04

At iterate  574    f=  2.80173D-01    |proj g|=  3.38429D-04

At iterate  575    f=  2.80173D-01    |proj g|=  1.15800D-03

At iterate  576    f=  2.80172D-01    |proj g|=  2.53433D-03

At iterate  577    f=  2.80172D-01    |proj g|=  3.51305D-03

At iterate  578    f=  2.80172D-01    |proj g|=  7.36105D-04

At iterate  579    f=  2.80171D-01    |proj g|=  1.77393D-03

At iterate  580    f=  2.80171D-01    |proj g|=  6.60898D-04

At iterate  581    f=  2.80171D-01    |proj g|=  5.66685D-04

At iterate  582    f=  2.80171D-01    |proj g|=  1.80708D-03

At iterate  583    f=  2.80171D-01    |proj g|=  1.24898D-03

At iterate  584    f=  2.80171D-01    |proj g|=  4.00304D-04

At iterate  585    f=  2.80171D-01    |proj g|=  3.92504D-04

At iterate  586    f=  2.80171D-01    |proj g|=  5.71813D-04

At iterate  587    f=  2.80171D-01    |proj g|=  8.43634D-04

At iterate  588    f=  2.80171D-01    |proj g|=  4.61954D-04

At iterate  589    f=  2.80171D-01    |proj g|=  1.61660D-03

At iterate  590    f=  2.80171D-01    |proj g|=  3.70790D-04

At iterate  591    f=  2.80171D-01    |proj g|=  7.90219D-04

At iterate  592    f=  2.80170D-01    |proj g|=  2.51636D-03

At iterate  593    f=  2.80170D-01    |proj g|=  5.56821D-04

At iterate  594    f=  2.80170D-01    |proj g|=  4.60717D-03

At iterate  595    f=  2.80170D-01    |proj g|=  8.73307D-04

At iterate  596    f=  2.80170D-01    |proj g|=  6.80166D-04

At iterate  597    f=  2.80170D-01    |proj g|=  7.16614D-04

At iterate  598    f=  2.80170D-01    |proj g|=  1.14793D-03

At iterate  599    f=  2.80170D-01    |proj g|=  1.55226D-03

At iterate  600    f=  2.80170D-01    |proj g|=  3.05380D-04

At iterate  601    f=  2.80170D-01    |proj g|=  1.43869D-04

At iterate  602    f=  2.80169D-01    |proj g|=  1.71251D-03

At iterate  603    f=  2.80169D-01    |proj g|=  2.48797D-03

At iterate  604    f=  2.80169D-01    |proj g|=  4.81694D-03

At iterate  605    f=  2.80169D-01    |proj g|=  2.51419D-03

At iterate  606    f=  2.80169D-01    |proj g|=  7.14723D-04

At iterate  607    f=  2.80168D-01    |proj g|=  2.93305D-03

At iterate  608    f=  2.80168D-01    |proj g|=  2.71175D-03

At iterate  609    f=  2.80168D-01    |proj g|=  3.20769D-03

At iterate  610    f=  2.80168D-01    |proj g|=  1.10639D-03

At iterate  611    f=  2.80168D-01    |proj g|=  1.38997D-03

At iterate  612    f=  2.80168D-01    |proj g|=  2.23309D-03

At iterate  613    f=  2.80168D-01    |proj g|=  1.53013D-03

At iterate  614    f=  2.80168D-01    |proj g|=  3.79672D-04

At iterate  615    f=  2.80168D-01    |proj g|=  6.22399D-04

At iterate  616    f=  2.80168D-01    |proj g|=  3.23335D-04

At iterate  617    f=  2.80167D-01    |proj g|=  6.89412D-04

At iterate  618    f=  2.80167D-01    |proj g|=  3.03673D-03

At iterate  619    f=  2.80167D-01    |proj g|=  2.56942D-03

At iterate  620    f=  2.80167D-01    |proj g|=  7.96178D-04

At iterate  621    f=  2.80167D-01    |proj g|=  1.83911D-04

At iterate  622    f=  2.80167D-01    |proj g|=  3.40439D-04

At iterate  623    f=  2.80167D-01    |proj g|=  4.54859D-04

At iterate  624    f=  2.80167D-01    |proj g|=  1.39745D-03

At iterate  625    f=  2.80167D-01    |proj g|=  3.07120D-04

At iterate  626    f=  2.80167D-01    |proj g|=  1.68288D-04

At iterate  627    f=  2.80167D-01    |proj g|=  1.78404D-04

At iterate  628    f=  2.80167D-01    |proj g|=  5.49462D-04

At iterate  629    f=  2.80167D-01    |proj g|=  7.68850D-05

At iterate  630    f=  2.80167D-01    |proj g|=  8.69459D-04

At iterate  631    f=  2.80167D-01    |proj g|=  2.60713D-04

At iterate  632    f=  2.80167D-01    |proj g|=  4.68934D-04

At iterate  633    f=  2.80167D-01    |proj g|=  8.75903D-04

At iterate  634    f=  2.80167D-01    |proj g|=  1.11579D-03

At iterate  635    f=  2.80167D-01    |proj g|=  3.67402D-04

At iterate  636    f=  2.80167D-01    |proj g|=  2.02096D-03

At iterate  637    f=  2.80167D-01    |proj g|=  2.87354D-04

At iterate  638    f=  2.80167D-01    |proj g|=  4.04267D-04

At iterate  639    f=  2.80167D-01    |proj g|=  7.11671D-04

At iterate  640    f=  2.80167D-01    |proj g|=  8.42498D-04

At iterate  641    f=  2.80167D-01    |proj g|=  2.00518D-03

At iterate  642    f=  2.80167D-01    |proj g|=  6.16057D-04

At iterate  643    f=  2.80167D-01    |proj g|=  1.57171D-04

At iterate  644    f=  2.80167D-01    |proj g|=  3.27085D-04

At iterate  645    f=  2.80167D-01    |proj g|=  6.66360D-04

At iterate  646    f=  2.80167D-01    |proj g|=  1.00716D-03

At iterate  647    f=  2.80167D-01    |proj g|=  3.33112D-04

At iterate  648    f=  2.80167D-01    |proj g|=  1.46526D-03

At iterate  649    f=  2.80167D-01    |proj g|=  3.11443D-04

At iterate  650    f=  2.80167D-01    |proj g|=  6.37446D-04

At iterate  651    f=  2.80167D-01    |proj g|=  9.78370D-04

At iterate  652    f=  2.80167D-01    |proj g|=  1.25845D-03

At iterate  653    f=  2.80167D-01    |proj g|=  6.99770D-04

At iterate  654    f=  2.80167D-01    |proj g|=  2.17212D-04

At iterate  655    f=  2.80167D-01    |proj g|=  3.36213D-04

At iterate  656    f=  2.80167D-01    |proj g|=  1.27330D-03

At iterate  657    f=  2.80167D-01    |proj g|=  1.49521D-03

At iterate  658    f=  2.80166D-01    |proj g|=  1.04914D-03

At iterate  659    f=  2.80166D-01    |proj g|=  4.62519D-03

At iterate  660    f=  2.80166D-01    |proj g|=  2.56204D-03

At iterate  661    f=  2.80166D-01    |proj g|=  3.47976D-04

At iterate  662    f=  2.80166D-01    |proj g|=  5.16679D-05

At iterate  663    f=  2.80166D-01    |proj g|=  1.27727D-04

At iterate  664    f=  2.80166D-01    |proj g|=  4.69331D-04

At iterate  665    f=  2.80166D-01    |proj g|=  2.06335D-04

At iterate  666    f=  2.80166D-01    |proj g|=  1.19006D-04

At iterate  667    f=  2.80166D-01    |proj g|=  1.02354D-04

At iterate  668    f=  2.80166D-01    |proj g|=  5.10453D-04

At iterate  669    f=  2.80166D-01    |proj g|=  5.60202D-04

At iterate  670    f=  2.80166D-01    |proj g|=  2.90077D-03

At iterate  671    f=  2.80166D-01    |proj g|=  1.39139D-03

At iterate  672    f=  2.80165D-01    |proj g|=  4.24854D-04

At iterate  673    f=  2.80165D-01    |proj g|=  6.38921D-04

At iterate  674    f=  2.80165D-01    |proj g|=  7.33263D-04

At iterate  675    f=  2.80165D-01    |proj g|=  1.98165D-03

At iterate  676    f=  2.80165D-01    |proj g|=  1.55762D-03

At iterate  677    f=  2.80165D-01    |proj g|=  1.03512D-03

At iterate  678    f=  2.80165D-01    |proj g|=  8.47018D-04

At iterate  679    f=  2.80164D-01    |proj g|=  1.21749D-03

At iterate  680    f=  2.80164D-01    |proj g|=  3.27718D-03

At iterate  681    f=  2.80164D-01    |proj g|=  5.82638D-03

At iterate  682    f=  2.80163D-01    |proj g|=  1.75996D-03

At iterate  683    f=  2.80163D-01    |proj g|=  2.57261D-04

At iterate  684    f=  2.80163D-01    |proj g|=  5.74554D-04

At iterate  685    f=  2.80163D-01    |proj g|=  5.96243D-04

At iterate  686    f=  2.80163D-01    |proj g|=  2.06871D-03

At iterate  687    f=  2.80163D-01    |proj g|=  1.22122D-03

At iterate  688    f=  2.80163D-01    |proj g|=  3.98342D-04

At iterate  689    f=  2.80163D-01    |proj g|=  1.69775D-04

At iterate  690    f=  2.80163D-01    |proj g|=  3.07945D-04

At iterate  691    f=  2.80163D-01    |proj g|=  7.48300D-04

At iterate  692    f=  2.80163D-01    |proj g|=  1.97647D-03

At iterate  693    f=  2.80163D-01    |proj g|=  1.58876D-03

At iterate  694    f=  2.80162D-01    |proj g|=  1.84105D-03

At iterate  695    f=  2.80162D-01    |proj g|=  2.39496D-03

At iterate  696    f=  2.80162D-01    |proj g|=  7.10773D-04

At iterate  697    f=  2.80162D-01    |proj g|=  4.93105D-04

At iterate  698    f=  2.80162D-01    |proj g|=  2.95769D-03

At iterate  699    f=  2.80162D-01    |proj g|=  2.45453D-03

At iterate  700    f=  2.80162D-01    |proj g|=  5.36794D-03

At iterate  701    f=  2.80162D-01    |proj g|=  3.08228D-03

At iterate  702    f=  2.80162D-01    |proj g|=  4.88398D-04

At iterate  703    f=  2.80162D-01    |proj g|=  3.47304D-04

At iterate  704    f=  2.80162D-01    |proj g|=  5.76900D-04

At iterate  705    f=  2.80161D-01    |proj g|=  7.69958D-04

At iterate  706    f=  2.80161D-01    |proj g|=  1.30786D-03

At iterate  707    f=  2.80161D-01    |proj g|=  1.04056D-03

At iterate  708    f=  2.80161D-01    |proj g|=  6.56258D-04

At iterate  709    f=  2.80161D-01    |proj g|=  1.75616D-03

At iterate  710    f=  2.80161D-01    |proj g|=  1.86225D-03

At iterate  711    f=  2.80161D-01    |proj g|=  3.67252D-04

At iterate  712    f=  2.80161D-01    |proj g|=  5.44313D-04

At iterate  713    f=  2.80161D-01    |proj g|=  3.25400D-03

At iterate  714    f=  2.80161D-01    |proj g|=  2.23050D-03

At iterate  715    f=  2.80161D-01    |proj g|=  6.94945D-04

At iterate  716    f=  2.80161D-01    |proj g|=  5.91068D-04

At iterate  717    f=  2.80160D-01    |proj g|=  1.57544D-03

At iterate  718    f=  2.80160D-01    |proj g|=  1.59591D-03

At iterate  719    f=  2.80160D-01    |proj g|=  2.22012D-03

At iterate  720    f=  2.80160D-01    |proj g|=  3.17065D-04

At iterate  721    f=  2.80160D-01    |proj g|=  1.53315D-04

At iterate  722    f=  2.80160D-01    |proj g|=  4.54730D-04

           * * *

Tit   = total number of iterations
Tnf   = total number of function evaluations
Tnint = total number of segments explored during Cauchy searches
Skip  = number of BFGS updates skipped
Nact  = number of active bounds at final generalized Cauchy point
Projg = norm of the final projected gradient
F     = final function value

           * * *

   N    Tit     Tnf  Tnint  Skip  Nact     Projg        F
   28    722    833      1     0     0   4.547D-04   2.802D-01
  F =  0.28016013029761216

CONVERGENCE: REL_REDUCTION_OF_F_<=_FACTR*EPSMCH
                           Logit Regression Results
==============================================================================
Dep. Variable:                      y   No. Observations:                29813
Model:                          Logit   Df Residuals:                    29785
Method:                           MLE   Df Model:                           27
Date:                Mon, 26 Oct 2026   Pseudo R-squ.:                  0.1901
Time:                        18:04:21   Log-Likelihood:                -8352.4
converged:                       True   LL-Null:                       -10313.
Covariance Type:            nonrobust   LLR p-value:                     0.000
=============================================================================================
                                coef    std err          z      P>|z|      [0.025      0.975]
---------------------------------------------------------------------------------------------
const                        -3.0688      0.196    -15.674      0.000      -3.453      -2.685
dist_goal_line               -0.0638      0.005    -12.885      0.000      -0.074      -0.054
lateral_offset               -0.0798      0.007    -11.484      0.000      -0.093      -0.066
angle_to_goal                 1.9023      0.109     17.526      0.000       1.690       2.115
is_home                      -0.0623      0.041     -1.501      0.133      -0.144       0.019
minute                        0.0015      0.001      1.902      0.057   -4.46e-05       0.003
score_diff                    0.1018      0.016      6.399      0.000       0.071       0.133
is_assisted                  -0.0924      0.089     -1.042      0.298      -0.266       0.081
is_penalty                    2.4086      0.224     10.743      0.000       1.969       2.848
is_open_play                  0.3662      0.096      3.801      0.000       0.177       0.555
from_corner                  -0.1692      0.106     -1.599      0.110      -0.377       0.038
left_foot                     0.5667      0.083      6.857      0.000       0.405       0.729
other_body_part              -0.1454      0.287     -0.506      0.613      -0.709       0.418
right_foot                    0.6009      0.080      7.518      0.000       0.444       0.758
last_action_aerial           -0.4046      0.136     -2.980      0.003      -0.671      -0.139
last_action_ball_recovery     1.1729      0.142      8.267      0.000       0.895       1.451
last_action_ball_touch        0.2693      0.170      1.584      0.113      -0.064       0.603
last_action_chipped           0.4802      0.138      3.471      0.001       0.209       0.751
last_action_cross             0.2435      0.118      2.067      0.039       0.013       0.474
last_action_dispossessed      0.2604      0.329      0.791      0.429      -0.385       0.906
last_action_head_pass         0.4313      0.157      2.755      0.006       0.125       0.738
last_action_lay_off          -0.2253      0.550     -0.410      0.682      -1.303       0.852
last_action_pass              0.6137      0.112      5.495      0.000       0.395       0.833
last_action_rebound           0.5512      0.101      5.453      0.000       0.353       0.749
last_action_standard          1.2224      0.194      6.286      0.000       0.841       1.603
last_action_tackle            0.5968      0.498      1.199      0.231      -0.379       1.573
last_action_take_on           0.9142      0.123      7.421      0.000       0.673       1.156
last_action_throughball       1.4341      0.141     10.205      0.000       1.159       1.710
=============================================================================================

Converged: True

In [6]:

# Diagnose rare categories and possible predictor redundancy

print("=== CATEGORY COUNTS ===")

for col in SHOT_FEATURES + BODY_FEATURES + LAST_ACTION_FEATURES:
    if col in train.columns:
        print(f"\n{col}")
        print(train[col].value_counts(dropna=False).head(10))

print("\n=== POSSIBLE REDUNDANCY ===")

# Check whether any binary predictors are identical or exact opposites
binary_features = [
    col for col in FULL_FEATURES
    if train[col].nunique() <= 2
]

for i, col1 in enumerate(binary_features):
    for col2 in binary_features[i + 1:]:
        a = train[col1].to_numpy()
        b = train[col2].to_numpy()

        if np.array_equal(a, b):
            print(f"Identical predictors: {col1} and {col2}")
        elif np.array_equal(a, 1 - b):
            print(f"Opposite predictors: {col1} and {col2}")

print("\n=== GOAL COUNTS IN CATEGORIES ===")

for col in SHOT_FEATURES + BODY_FEATURES + LAST_ACTION_FEATURES:
    if col in train.columns:
        print(f"\n{col}")
        print(pd.crosstab(train[col], train["result"]))

=== CATEGORY COUNTS ===

is_assisted
1    22066
0     7747
Name: is_assisted, dtype: int64

is_penalty
0    29504
1      309
Name: is_penalty, dtype: int64

is_open_play
1    21724
0     8089
Name: is_open_play, dtype: int64

from_corner
0    24743
1     5070
Name: from_corner, dtype: int64

is_free_kick
0    28894
1      919
Name: is_free_kick, dtype: int64

left_foot
0    20129
1     9684
Name: left_foot, dtype: int64

other_body_part
0    29680
1      133
Name: other_body_part, dtype: int64

right_foot
1    14968
0    14845
Name: right_foot, dtype: int64

last_action_aerial
0    27349
1     2464
Name: last_action_aerial, dtype: int64

last_action_ball_recovery
0    29051
1      762
Name: last_action_ball_recovery, dtype: int64

last_action_ball_touch
0    29166
1      647
Name: last_action_ball_touch, dtype: int64

last_action_chipped
0    28313
1     1500
Name: last_action_chipped, dtype: int64

last_action_cross
0    26075
1     3738
Name: last_action_cross, dtype: int64

last_action_dispossessed
0    29663
1      150
Name: last_action_dispossessed, dtype: int64

last_action_head_pass
0    29117
1      696
Name: last_action_head_pass, dtype: int64

last_action_lay_off
0    29703
1      110
Name: last_action_lay_off, dtype: int64

last_action_pass
0    18724
1    11089
Name: last_action_pass, dtype: int64

last_action_rebound
0    28365
1     1448
Name: last_action_rebound, dtype: int64

last_action_standard
0    28585
1     1228
Name: last_action_standard, dtype: int64

last_action_tackle
0    29755
1       58
Name: last_action_tackle, dtype: int64

last_action_take_on
0    28446
1     1367
Name: last_action_take_on, dtype: int64

last_action_throughball
0    29124
1      689
Name: last_action_throughball, dtype: int64

=== POSSIBLE REDUNDANCY ===

=== GOAL COUNTS IN CATEGORIES ===

is_assisted
result           0     1
is_assisted
0             6799   948
1            19743  2323

is_penalty
result          0     1
is_penalty
0           26487  3017
1              55   254

is_open_play
result            0     1
is_open_play
0              7187   902
1             19355  2369

from_corner
result           0     1
from_corner
0            21911  2832
1             4631   439

is_free_kick
result            0     1
is_free_kick
0             25670  3224
1               872    47

left_foot
result         0     1
left_foot
0          17922  2207
1           8620  1064

other_body_part
result               0     1
other_body_part
0                26426  3254
1                  116    17

right_foot
result          0     1
right_foot
0           13232  1613
1           13310  1658

last_action_aerial
result                  0     1
last_action_aerial
0                   24225  3124
1                    2317   147

last_action_ball_recovery
result                         0     1
last_action_ball_recovery
0                          25863  3188
1                            679    83

last_action_ball_touch
result                      0     1
last_action_ball_touch
0                       25953  3213
1                         589    58

last_action_chipped
result                   0     1
last_action_chipped
0                    25194  3119
1                     1348   152

last_action_cross
result                 0     1
last_action_cross
0                  23275  2800
1                   3267   471

last_action_dispossessed
result                        0     1
last_action_dispossessed
0                         26403  3260
1                           139    11

last_action_head_pass
result                     0     1
last_action_head_pass
0                      25946  3171
1                        596   100

last_action_lay_off
result                   0     1
last_action_lay_off
0                    26436  3267
1                      106     4

last_action_pass
result                0     1
last_action_pass
0                 16451  2273
1                 10091   998

last_action_rebound
result                   0     1
last_action_rebound
0                    25406  2959
1                     1136   312

last_action_standard
result                    0     1
last_action_standard
0                     25615  2970
1                       927   301

last_action_tackle
result                  0     1
last_action_tackle
0                   26491  3264
1                      51     7

last_action_take_on
result                   0     1
last_action_take_on
0                    25347  3099
1                     1195   172

last_action_throughball
result                       0     1
last_action_throughball
0                        26025  3099
1                          517   172

In [7]:
from sklearn.metrics import (
    brier_score_loss,
    log_loss,
    roc_auc_score
)

# Core model: spatial predictors only
X_train_core = sm.add_constant(
    train[CORE_FEATURES],
    has_constant="add"
)
X_val_core = sm.add_constant(
    val[CORE_FEATURES],
    has_constant="add"
)

core_fit = sm.Logit(
    train["result"],
    X_train_core
).fit(disp=False)

# Full model: all selected predictors
X_train_full = sm.add_constant(
    train[FULL_FEATURES],
    has_constant="add"
)
X_val_full = sm.add_constant(
    val[FULL_FEATURES],
    has_constant="add"
)

full_fit = sm.Logit(
    train["result"],
    X_train_full
).fit(method="lbfgs", maxiter=1000, disp=False)

# Validation predictions
y_val = val["result"].to_numpy()

p_core = np.asarray(core_fit.predict(X_val_core))
p_full = np.asarray(full_fit.predict(X_val_full))

# Compare out-of-sample performance
results = pd.DataFrame({
    "Model": ["Core", "Full"],
    "ROC_AUC": [
        roc_auc_score(y_val, p_core),
        roc_auc_score(y_val, p_full)
    ],
    "Brier_Score": [
        brier_score_loss(y_val, p_core),
        brier_score_loss(y_val, p_full)
    ],
    "Log_Loss": [
        log_loss(y_val, p_core),
        log_loss(y_val, p_full)
    ]
})

results

  Model   ROC_AUC  Brier_Score  Log_Loss
0  Core  0.718191     0.089532  0.313183
1  Full  0.780692     0.081090  0.285322